---
title: "Supplementary Figure S5 - Cross-correlation of HPV-16 gene-level read pairs and insert sizes in the training set"
author:
  - name: David N Brown, Bill H Diplas
    affiliation: Memorial Sloan Kettering Cancer Center
output:
  html_document:
    theme: cerulean
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
suppressPackageStartupMessages({
  library("ggplot2")
  library("readr")
  library("dplyr")
  library("magrittr")
  library("reshape2")
  library("corrplot")
  library("RColorBrewer")
  library("fuzzyjoin")
})

# --- Data paths ---
url_manifest                 <- "../data/manifest.txt"
url_mrd_summary              <- "../data/TM-2021-MSK-002_MRD_Results_Summary_20220825.txt"
url_preanalytical_conditions <- "../data/pre-analytical_conditions.txt"
url_hpv_type                 <- "../data/TM-2021-MSK-002_HPV_Typing_WES_WGS.txt"
url_no_node_dissection       <- "../data/patients_0_nodal_dissection.txt"
url_mutation_summary         <- "../data/mutation_summary.maf"
url_insert_metrics_by_gene   <- "../data/insert_metrics_by_gene.txt"
url_hs_target_metrics        <- "../data/hs_metrics_target.txt"
url_hs_target_metrics_ft     <- "../data/hs_metrics_target_ft.txt"
url_bed_file                 <- "../data/hpv_31_33_35H_16_18.bed"

target_contigs <- c(
  "HPV-16" = "NC001526.4",
  "HPV-18" = "NC001357.1",
  "HPV-31" = "J04353.1",
  "HPV-33" = "M12732.1",
  "HPV-35" = "X74477.1"
)

contig_to_hpv <- c(
  "J04353.1"   = "HPV-31",
  "M12732.1"   = "HPV-33",
  "NC001357.1" = "HPV-18",
  "NC001526.4" = "HPV-16",
  "X74477.1"   = "HPV-35"
)

gene_order <- c("E6", "E7", "E1", "E2", "E5", "L1")
```

```{r load_shared_data, eval = TRUE, include = FALSE}

manifest_raw <- readr::read_tsv(
  url_manifest, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::filter(!is.na(bam_file_name_hpv)) %>%
  dplyr::mutate(sample_uuid = paste0(sample_id_mskcc, "-", sample_id_invitae))

preanalytical_conditions <- readr::read_tsv(
  url_preanalytical_conditions, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

mrd_smry <- readr::read_tsv(
  url_mrd_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    sample_uuid = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE),
    sample_name = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE)
  )

hpv_smry <- readr::read_tsv(
  url_hpv_type, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    patient_id_mskcc = gsub("-T", "", patient_name, fixed = TRUE),
    patient_id_mskcc = gsub("155salv", "155", patient_id_mskcc, fixed = TRUE),
    hpv_type_wes     = gsub("HPV", "HPV-", hpv_type_wes, fixed = TRUE),
    hpv_type_wgs     = gsub("HPV", "HPV-", hpv_type_wgs, fixed = TRUE),
    hpv_type_wes_wgs = gsub("HPV", "HPV-", hpv_type_wes_wgs, fixed = TRUE),
    hpv_type_wes_wgs = dplyr::coalesce(hpv_type_wes_wgs, "Unknown")
  )

nodal_dissection_smry <- readr::read_tsv(
  url_no_node_dissection, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(patient_id_mskcc = sample)

manifest <- manifest_raw %>%
  dplyr::left_join(preanalytical_conditions, by = "sample_id_mskcc") %>%
  dplyr::mutate(
    patient_id_mskcc = dplyr::case_when(
      is.na(patient_id_mskcc) & sample_id_mskcc == "21-144-03654" ~ "CTMS-164",
      TRUE ~ patient_id_mskcc
    ),
    sample_name = paste0(sample_id_mskcc, "-", sample_id_invitae)
  ) %>%
  dplyr::left_join(hpv_smry, by = "patient_id_mskcc")

mutation_smry <- readr::read_tsv(
  url_mutation_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

bed_file <- readr::read_tsv(
  url_bed_file, col_names = FALSE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(chromosome = X1, start = X2, end = X3, gene_name = X4) %>%
  dplyr::select(-X5) %>%
  dplyr::filter(gene_name != "E1^E4")

insert_metrics_by_gene <- readr::read_tsv(
  url_insert_metrics_by_gene, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(sample_name = SAMPLE_NAME) %>%
  dplyr::filter(TARGET_REGION != "NC001526.4:3372-4794")

hs_metrics <- readr::read_tsv(
  url_hs_target_metrics, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::select(
    sample_name    = SAMPLE_NAME,
    chromosome     = chrom,
    start, end,
    aligned_reads  = read_count
  ) %>%
  dplyr::filter(chromosome %in% target_contigs) %>%
  fuzzyjoin::genome_left_join(bed_file, by = c("chromosome", "start", "end")) %>%
  dplyr::select(-chromosome.y, -start.y, -end.y) %>%
  dplyr::rename(chromosome = chromosome.x, start = start.x, end = end.x)

hs_metrics_ft <- readr::read_tsv(
  url_hs_target_metrics_ft, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::select(
    sample_name     = SAMPLE_NAME,
    chromosome      = chrom,
    start, end,
    aligned_reads   = read_count,
    fragment_length = FRAGMENT_LENGTH
  ) %>%
  dplyr::filter(chromosome %in% target_contigs) %>%
  fuzzyjoin::genome_left_join(bed_file, by = c("chromosome", "start", "end")) %>%
  dplyr::select(-chromosome.y, -start.y, -end.y) %>%
  dplyr::rename(chromosome = chromosome.x, start = start.x, end = end.x)

# --- ctDNA-positive training set ---
smry_t_pos <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(mean_af = mean(t_maf), .groups = "drop") %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode) %>%
  dplyr::filter(mean_af > 0.05) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::filter(hpv_type_wes_wgs %in% names(target_contigs)) %>%
  dplyr::left_join(
    dplyr::select(mrd_smry, sample_name, `MRD-Landmark_Result`),
    by = "sample_name"
  ) %>%
  dplyr::filter(`MRD-Landmark_Result` == "PRESENT") %>%
  dplyr::mutate(Is_ctDNA = "+ve")

# --- ctDNA-negative training set ---
neg_candidates <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(mean_af = mean(t_maf), max_af = max(t_maf), .groups = "drop") %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode) %>%
  dplyr::filter(mean_af < 0.0001, max_af < 0.001) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::left_join(nodal_dissection_smry, by = "patient_id_mskcc") %>%
  dplyr::filter(nd_event == 0, timepoint_days_since_start_of_RT > 730)

latest_per_patient <- neg_candidates %>%
  dplyr::group_by(patient_id_mskcc) %>%
  dplyr::summarize(
    timepoint_days_since_start_of_RT = max(timepoint_days_since_start_of_RT),
    .groups = "drop"
  )

smry_t_neg <- neg_candidates %>%
  dplyr::inner_join(latest_per_patient, by = c("patient_id_mskcc", "timepoint_days_since_start_of_RT")) %>%
  dplyr::left_join(
    dplyr::select(mrd_smry, sample_name, `MRD-Landmark_Result`),
    by = "sample_name"
  ) %>%
  dplyr::filter(`MRD-Landmark_Result` == "ABSENT") %>%
  dplyr::mutate(Is_ctDNA = "-ve")

shared_cols <- intersect(colnames(smry_t_pos), colnames(smry_t_neg))
smry_ft <- dplyr::bind_rows(
  dplyr::select(smry_t_pos, all_of(shared_cols)),
  dplyr::select(smry_t_neg, all_of(shared_cols))
)

# --- Shared base: insert metrics joined to mutation AF and manifest ---
mut_af_smry <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(
    mean_af   = mean(t_maf),
    median_af = median(t_maf),
    max_af    = max(t_maf),
    .groups   = "drop"
  ) %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode)

smry_base <- insert_metrics_by_gene %>%
  dplyr::left_join(mut_af_smry, by = "sample_name") %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::mutate(hpv_type_wes_wgs = dplyr::coalesce(hpv_type_wes_wgs, "Unknown")) %>%
  dplyr::mutate(
    chromosome = vapply(TARGET_REGION, function(x) strsplit(x, ":", fixed = TRUE)[[1]][1], character(1)),
    start      = vapply(TARGET_REGION, function(x) strsplit(x, ":|-", perl = TRUE)[[1]][2], character(1)),
    end        = vapply(TARGET_REGION, function(x) strsplit(x, ":|-", perl = TRUE)[[1]][3], character(1))
  ) %>%
  readr::type_convert() %>%
  dplyr::left_join(bed_file, by = c("chromosome", "start", "end")) %>%
  dplyr::mutate(
    chromosome    = dplyr::recode(chromosome, !!!contig_to_hpv),
    mean_af       = dplyr::if_else(mean_af   == 0, 1e-6, mean_af),
    median_af     = dplyr::if_else(median_af == 0, 1e-6, median_af),
    max_af        = dplyr::if_else(max_af    == 0, 1e-6, max_af),
    start_end     = paste0(start, ":", end),
    aligned_reads = log10(READ_PAIRS + 1),
    insert_size   = log10(MEAN_INSERT_SIZE + 1)
  ) %>%
  dplyr::left_join(dplyr::select(smry_ft, sample_name, Is_ctDNA), by = "sample_name") %>%
  dplyr::filter(!is.na(Is_ctDNA)) %>%
  dplyr::mutate(
    Is_ctDNA = dplyr::case_when(
      hpv_type_wes_wgs == "HPV-16" & Is_ctDNA == "+ve" ~ "+ve",
      TRUE ~ "-ve"
    ),
    Is_ctDNA = factor(Is_ctDNA, levels = c("+ve", "-ve"), ordered = TRUE)
  ) %>%
  dplyr::filter(chromosome == "HPV-16", hpv_type_wes_wgs == "HPV-16")
```

```{r build_corrplots, eval = TRUE, include = FALSE}

# --- Helper: build pairwise Spearman correlation matrix from a wide dcast tibble ---
build_corr_matrix <- function(wide_df) {
  # Identify gene columns (everything after sample_name and Is_ctDNA)
  gene_cols <- colnames(wide_df)[-c(1, 2)]
  gene_cols <- gene_cols[order(vapply(gene_cols, function(x) strsplit(x, "_")[[1]][2], character(1)))]

  pairs <- do.call(rbind, lapply(seq_len(length(gene_cols) - 1), function(i) {
    do.call(rbind, lapply(seq(i + 1, length(gene_cols)), function(j) {
      xi <- wide_df[[gene_cols[i]]]
      xj <- wide_df[[gene_cols[j]]]
      dplyr::tibble(
        rho  = cor.test(xi, xj, method = "spearman")$estimate,
        xlab = gene_cols[i],
        ylab = gene_cols[j]
      )
    }))
  }))

  all_genes <- unique(c(pairs$xlab, pairs$ylab))
  m <- matrix(1, nrow = length(all_genes), ncol = length(all_genes),
              dimnames = list(all_genes, all_genes))
  for (k in seq_len(nrow(pairs))) {
    m[pairs$xlab[k], pairs$ylab[k]] <- pairs$rho[k]
    m[pairs$ylab[k], pairs$xlab[k]] <- pairs$rho[k]
  }

  # Simplify row/col names to gene label (e.g. "E1_1:1950" → "E1")
  gene_labels <- vapply(rownames(m), function(x) strsplit(x, "_")[[1]][1], character(1))
  rownames(m) <- gene_labels
  colnames(m) <- gene_labels
  m
}

# --- Helper: render a corrplot with shared styling ---
draw_corrplot <- function(m) {
  corrplot::corrplot(
    corr        = m[gene_order, gene_order],
    method      = "circle",
    type        = "lower",
    col         = colorRampPalette(RColorBrewer::brewer.pal(n = 11, name = "RdBu"))(25),
    is.corr     = FALSE,
    diag        = FALSE,
    addgrid.col = NA,
    addCoef.col = "black",
    order       = "original",
    number.cex  = 0.55,
    number.font = 1,
    tl.cex      = 1,
    tl.col      = "black",
    cl.pos      = "r",
    cl.ratio    = 0.25,
    cl.length   = 7
  )
}

# --- S5a: aligned read pairs ---
wide_reads <- smry_base %>%
  reshape2::dcast(
    formula   = sample_name + Is_ctDNA ~ gene_name + start_end,
    value.var = "aligned_reads"
  )

corr_matrix_reads <- build_corr_matrix(wide_reads)

# --- S5b: mean insert size ---
wide_insert <- smry_base %>%
  reshape2::dcast(
    formula   = sample_name + Is_ctDNA ~ gene_name + start_end,
    value.var = "insert_size"
  )

corr_matrix_insert <- build_corr_matrix(wide_insert)
```

<br/>

```{r plot_corrplot_reads, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 5, fig.width = 5, fig.cap = '<br/>**Supplementary Figure S5a** Cross-correlation matrix of HPV-16 gene-level aligned read pairs across training set samples.'}

draw_corrplot(corr_matrix_reads)
```

<br/>

```{r plot_corrplot_insert_size, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 5, fig.width = 5, fig.cap = '<br/>**Supplementary Figure S5b** Cross-correlation matrix of HPV-16 gene-level mean insert sizes across training set samples.'}

draw_corrplot(corr_matrix_insert)
```
