---
title: "Figure 4 - Dynamic response assessment using dual-assay ctDNA and imaging in HPV-associated oropharyngeal cancers"
author:
  - name: David N Brown, Bill H Diplas
    affiliation: Memorial Sloan Kettering Cancer Center
output:
  html_document:
    theme: cerulean
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
suppressPackageStartupMessages({
  library("ggplot2")
  library("readr")
  library("dplyr")
  library("magrittr")
  library("tidyr")
  library("reshape2")
  library("ggridges")
  library("ggpubr")
  library("viridis")
  library("corrplot")
  library("RColorBrewer")
  library("gridExtra")
  library("MASS")
})

# --- Data paths ---
url_manifest                 <- "../data/manifest.txt"
url_preanalytical_conditions <- "../data/pre-analytical_conditions.txt"
url_mrd_summary              <- "../data/TM-2021-MSK-002_MRD_Results_Summary_20220825.txt"
url_mutation_summary         <- "../data/mutation_summary.maf"
url_hpv_type                 <- "../data/TM-2021-MSK-002_HPV_Typing_WES_WGS.txt"
url_no_node_dissection       <- "../data/patients_0_nodal_dissection.txt"
url_clinical                 <- "../data/clinical.txt"
url_idx_metrics_ft           <- "../data/idx_metrics_ft.txt"
url_posterior_probs          <- "../res/Posterior_Probability_ALL.txt"

target_contigs <- c(
  "HPV-16" = "NC001526.4",
  "HPV-18" = "NC001357.1",
  "HPV-31" = "J04353.1",
  "HPV-33" = "M12732.1",
  "HPV-35" = "X74477.1"
)

FRAGMENT_LENGTH_THRESHOLD <- 37

scientific_10 <- function(x) {
  parse(text = gsub("+", "", gsub("e", " %.% 10^", scales::scientific_format()(x)), fixed = TRUE))
}

scientific_1e <- function(x) {
  parse(text = gsub("+", "", gsub("1e", " 10^", scales::scientific_format()(x)), fixed = TRUE))
}

# --- Shared timepoint helpers (carried from S9) ---
recode_weeks <- function(x) {
  dplyr::case_when(
    x %in% c("wk0", "Pre-treatment") ~ "0",
    x == "wk1" ~ "1",
    x == "wk2" ~ "2",
    x == "wk3" ~ "3"
  )
}

normalise_to_baseline <- function(df, measure_col, patient_col = "patient_id_mskcc",
                                   week_col = "timepoint_weeks_since_start_of_RT") {
  baseline <- df %>%
    dplyr::filter(.data[[week_col]] == 0) %>%
    dplyr::select(all_of(c(patient_col, measure_col))) %>%
    dplyr::rename(baseline = !!measure_col)
  df %>%
    dplyr::left_join(baseline, by = patient_col) %>%
    dplyr::mutate(!!measure_col := .data[[measure_col]] / baseline) %>%
    dplyr::select(-baseline)
}

# --- Shared wide-pivot helper (carried from S12) ---
make_wide <- function(df, value_col, prefix) {
  df %>%
    dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
    dplyr::summarize(v = mean(.data[[value_col]] + 1e-5, na.rm = TRUE), .groups = "drop") %>%
    reshape2::dcast(
      formula       = patient_id_mskcc ~ timepoint_weeks_since_start_of_RT,
      fun.aggregate = function(x) mean(x, na.rm = TRUE),
      fill          = NaN,
      value.var     = "v"
    ) %>%
    dplyr::select(patient_id_mskcc, `Pre-treatment`, wk1, wk2, wk3) %>%
    readr::type_convert() %>%
    dplyr::rename(
      !!paste0(prefix, "_wk0") := `Pre-treatment`,
      !!paste0(prefix, "_wk1") := wk1,
      !!paste0(prefix, "_wk2") := wk2,
      !!paste0(prefix, "_wk3") := wk3
    )
}

# --- Shared ridge plot structure for Figure 4a panels ---
ridge_timepoints <- c("wk5", "wk3", "wk2", "wk1", "Pre-treatment")
ridge_labels     <- c("Week 5", "Week 3", "Week 2", "Week 1", "Pre-treatment")

ridge_plot <- function(df, x_col, x_scale, x_lab, bandwidth, scale = 1.5,
                       show_y_labels = TRUE) {
  df %>%
    dplyr::filter(timepoint_weeks_since_start_of_RT %in% ridge_timepoints) %>%
    dplyr::mutate(
      timepoint_weeks_since_start_of_RT = factor(
        timepoint_weeks_since_start_of_RT,
        levels  = ridge_timepoints,
        ordered = TRUE
      )
    ) %>%
    ggplot(aes(
      x    = .data[[x_col]],
      y    = timepoint_weeks_since_start_of_RT,
      fill = timepoint_weeks_since_start_of_RT
    )) +
    geom_density_ridges2(
      stat = "density_ridges", bandwidth = bandwidth,
      scale = scale, color = "black", alpha = 1
    ) +
    scale_fill_viridis(discrete = TRUE) +
    x_scale +
    scale_y_discrete(
      breaks = ridge_timepoints,
      labels = if (show_y_labels) ridge_labels else rep("", 5)
    ) +
    xlab(x_lab) +
    ylab("") +
    theme_classic() +
    theme(
      axis.title.x = element_text(margin = ggplot2::margin(t = 20)),
      axis.title.y = element_text(margin = ggplot2::margin(r = 20)),
      axis.text.x  = element_text(size = 10),
      axis.text.y  = element_text(size = 10)
    ) +
    guides(fill = "none") +
    coord_cartesian(clip = "off")
}
```

```{r load_shared_data, eval = TRUE, include = FALSE}

manifest_raw <- readr::read_tsv(
  url_manifest, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::filter(!is.na(bam_file_name_hpv)) %>%
  dplyr::mutate(sample_uuid = paste0(sample_id_mskcc, "-", sample_id_invitae))

preanalytical_conditions <- readr::read_tsv(
  url_preanalytical_conditions, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

mrd_smry <- readr::read_tsv(
  url_mrd_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    sample_uuid = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE),
    sample_name = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE)
  )

hpv_smry <- readr::read_tsv(
  url_hpv_type, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    patient_id_mskcc = gsub("-T", "", patient_name, fixed = TRUE),
    patient_id_mskcc = gsub("155salv", "155", patient_id_mskcc, fixed = TRUE),
    hpv_type_wes     = gsub("HPV", "HPV-", hpv_type_wes, fixed = TRUE),
    hpv_type_wgs     = gsub("HPV", "HPV-", hpv_type_wgs, fixed = TRUE),
    hpv_type_wes_wgs = gsub("HPV", "HPV-", hpv_type_wes_wgs, fixed = TRUE),
    hpv_type_wes_wgs = dplyr::coalesce(hpv_type_wes_wgs, "Unknown")
  )

nodal_dissection_smry <- readr::read_tsv(
  url_no_node_dissection, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(patient_id_mskcc = sample)

manifest <- manifest_raw %>%
  dplyr::left_join(preanalytical_conditions, by = "sample_id_mskcc") %>%
  dplyr::mutate(
    patient_id_mskcc = dplyr::case_when(
      is.na(patient_id_mskcc) & sample_id_mskcc == "21-144-03654" ~ "CTMS-164",
      TRUE ~ patient_id_mskcc
    ),
    sample_name = paste0(sample_id_mskcc, "-", sample_id_invitae)
  ) %>%
  dplyr::left_join(hpv_smry, by = "patient_id_mskcc")

mutation_smry <- readr::read_tsv(
  url_mutation_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

clinical <- readr::read_tsv(
  url_clinical, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

posterior_probs <- readr::read_tsv(
  url_posterior_probs, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = floor(timepoint_days_since_start_of_RT / 7),
    timepoint_weeks_since_start_of_RT = dplyr::case_when(
      timepoint_weeks_since_start_of_RT < 0 ~ "Pre-treatment",
      TRUE ~ paste0("wk", timepoint_weeks_since_start_of_RT)
    )
  )

# --- Per-sample mutation AF summary ---
mut_af_smry <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(mean_af = mean(t_maf), .groups = "drop") %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode)

# --- Index metrics at target fragment length ---
idx_metrics_ft <- readr::read_tsv(
  url_idx_metrics_ft, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::select(
    sample_name     = SAMPLE_NAME,
    contig          = CHROMOSOME,
    aligned_reads   = ALIGNED_READS,
    fragment_length = FRAGMENT_LENGTH
  ) %>%
  dplyr::left_join(
    dplyr::tibble(contig = target_contigs, chromosome = names(target_contigs)),
    by = "contig"
  ) %>%
  dplyr::filter(fragment_length == FRAGMENT_LENGTH_THRESHOLD, !is.na(chromosome)) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::filter(chromosome == hpv_type_wes_wgs) %>%
  dplyr::left_join(mut_af_smry, by = "sample_name") %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = floor(timepoint_days_since_start_of_RT / 7),
    timepoint_weeks_since_start_of_RT = dplyr::case_when(
      timepoint_weeks_since_start_of_RT < 0 ~ "Pre-treatment",
      TRUE ~ paste0("wk", timepoint_weeks_since_start_of_RT)
    )
  )

# --- Per-patient HPV type (used by ridge plots) ---
hpv_type_per_patient <- manifest %>%
  dplyr::group_by(patient_id_mskcc) %>%
  dplyr::summarize(hpv_type_wes_wgs = unique(hpv_type_wes_wgs), .groups = "drop")

# --- Helper: build per-week MRD detection summary from manifest ---
make_mrd_detect <- function() {
  manifest %>%
    dplyr::left_join(mrd_smry, by = "sample_name") %>%
    dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
    dplyr::mutate(
      timepoint_weeks_since_start_of_RT = floor(timepoint_days_since_start_of_RT / 7),
      timepoint_weeks_since_start_of_RT = dplyr::case_when(
        timepoint_weeks_since_start_of_RT < 0 ~ "Pre-treatment",
        TRUE ~ paste0("wk", timepoint_weeks_since_start_of_RT)
      )
    )
}
```

```{r build_plots_F4a, eval = TRUE, include = FALSE}

# --- F4a: ridge density plots across weekly timepoints ---
plot_mri <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    `Pre-treatment` = MRI_rawdata_wk0,
    wk1 = MRI_rawdata_wk1, wk2 = MRI_rawdata_wk2,
    wk3 = MRI_rawdata_wk3, wk5 = MRI_rawdata_wk4
  ) %>%
  reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "MRI_volume") %>%
  dplyr::left_join(hpv_type_per_patient, by = "patient_id_mskcc") %>%
  tidyr::drop_na() %>%
  dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
  dplyr::mutate(MRI_volume = MRI_volume * 0.001) %>%
  ridge_plot(
    x_col         = "MRI_volume",
    x_scale       = scale_x_log10(labels = scientific_10),
    x_lab         = expression("MRI Volume (" ~ cm^3 ~ ")"),
    bandwidth     = 0.095,
    show_y_labels = TRUE
  )

plot_adc <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    `Pre-treatment` = ADC_Mean_wk0,
    wk1 = ADC_Mean_wk1, wk2 = ADC_Mean_wk2,
    wk3 = ADC_Mean_wk3, wk5 = ADC_Mean_wk4
  ) %>%
  reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "ADC") %>%
  dplyr::left_join(hpv_type_per_patient, by = "patient_id_mskcc") %>%
  tidyr::drop_na() %>%
  dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
  ridge_plot(
    x_col         = "ADC",
    x_scale       = scale_x_log10(labels = scientific_10),
    x_lab         = expression("ADC (" %.% 10^-3 ~ mm^2 ~ sec^-1 ~ ")"),
    bandwidth     = 0.025,
    show_y_labels = FALSE
  )

plot_ctdna <- idx_metrics_ft %>%
  dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
  dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(mean_af = mean(mean_af), .groups = "drop") %>%
  dplyr::mutate(mean_af_pct = (mean_af * 100) + 1e-3) %>%
  ridge_plot(
    x_col     = "mean_af_pct",
    x_scale   = scale_x_log10(
      limits = c(NA, 110),
      breaks = c(0.001, 0.01, 0.1, 1, 10, 100),
      labels = scientific_1e
    ),
    x_lab         = "Mean PCM AF (%)",
    bandwidth     = 0.45,
    scale         = 2.65,
    show_y_labels = FALSE
  ) +
  theme(axis.title.x = element_text(margin = ggplot2::margin(t = 25)))

plot_chpv <- idx_metrics_ft %>%
  dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
  dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(aligned_reads = mean(log10(aligned_reads)), .groups = "drop") %>%
  ridge_plot(
    x_col     = "aligned_reads",
    x_scale   = scale_x_continuous(
      limits = c(1, 7),
      breaks = c(2, 3, 4, 5, 6, 7),
      labels = scientific_1e(10^c(2, 3, 4, 5, 6, 7))
    ),
    x_lab         = "cfDNA Aligned HPV Read Pairs",
    bandwidth     = 0.35,
    scale         = 1.75,
    show_y_labels = FALSE
  ) +
  theme(axis.title.x = element_text(margin = ggplot2::margin(t = 25)))
```

```{r build_plot_F4c, eval = TRUE, include = FALSE}

# --- F4c: CTMS-161 individual patient tracking ---
# PCM: mean AF normalised to pre-treatment
p_mrd <- idx_metrics_ft %>%
  dplyr::left_join(
    dplyr::select(mrd_smry, sample_name, `MRD-Monitoring_Result`),
    by = "sample_name"
  ) %>%
  dplyr::mutate(
    Is_ctDNA = dplyr::case_when(
      `MRD-Monitoring_Result` == "PRESENT" ~ "+ve",
      `MRD-Monitoring_Result` == "ABSENT"  ~ "-ve"
    )
  ) %>%
  dplyr::filter(
    patient_id_mskcc == "CTMS-161",
    timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")
  ) %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = recode_weeks(timepoint_weeks_since_start_of_RT)
  ) %>%
  readr::type_convert() %>%
  dplyr::select(
    patient_id_mskcc, timepoint_weeks_since_start_of_RT, measure = mean_af, Is_ctDNA
  ) %>%
  normalise_to_baseline("measure") %>%
  dplyr::mutate(assay = "PCM")

# HPV: aligned reads normalised to pre-treatment
p_hpv <- idx_metrics_ft %>%
  dplyr::left_join(
    dplyr::select(posterior_probs, sample_name, Is_ctDNA),
    by = "sample_name"
  ) %>%
  dplyr::filter(
    patient_id_mskcc == "CTMS-161",
    timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")
  ) %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = recode_weeks(timepoint_weeks_since_start_of_RT)
  ) %>%
  readr::type_convert() %>%
  dplyr::select(
    patient_id_mskcc, timepoint_weeks_since_start_of_RT, measure = aligned_reads, Is_ctDNA
  ) %>%
  normalise_to_baseline("measure") %>%
  dplyr::mutate(assay = "HPV")

# MRI volume normalised and rescaled
p_mri <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    `Pre-treatment` = MRI_rawdata_wk0,
    wk1 = MRI_rawdata_wk1, wk2 = MRI_rawdata_wk2, wk3 = MRI_rawdata_wk3
  ) %>%
  reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "measure") %>%
  dplyr::filter(
    patient_id_mskcc == "CTMS-161",
    timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")
  ) %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = recode_weeks(timepoint_weeks_since_start_of_RT)
  ) %>%
  readr::type_convert() %>%
  normalise_to_baseline("measure") %>%
  dplyr::mutate(
    measure  = dplyr::if_else((measure - 1) < 0, 0, measure - 1),
    Is_ctDNA = "Not Applicable",
    assay    = "MRI"
  )

# ADC normalised and rescaled
p_adc <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    `Pre-treatment` = ADC_Mean_wk0,
    wk1 = ADC_Mean_wk1, wk2 = ADC_Mean_wk2, wk3 = ADC_Mean_wk3
  ) %>%
  reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "measure") %>%
  dplyr::filter(
    patient_id_mskcc == "CTMS-161",
    timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")
  ) %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = recode_weeks(timepoint_weeks_since_start_of_RT)
  ) %>%
  readr::type_convert() %>%
  normalise_to_baseline("measure") %>%
  dplyr::mutate(
    measure  = dplyr::if_else((measure - 1) < 0, 0, 4 * (measure - 1)),
    Is_ctDNA = "Not Applicable",
    assay    = "ADC"
  )

plot_ctms161 <- dplyr::bind_rows(p_mrd, p_hpv, p_mri, p_adc) %>%
  dplyr::mutate(
    measure = measure * 100,
    assay   = factor(assay, levels = c("PCM", "HPV", "MRI", "ADC"), ordered = TRUE)
  ) %>%
  ggplot(aes(
    x     = timepoint_weeks_since_start_of_RT,
    y     = measure,
    shape = Is_ctDNA,
    color = assay
  )) +
  geom_line(
    mapping     = aes(x = timepoint_weeks_since_start_of_RT, y = measure, color = assay),
    stat        = "identity",
    linewidth   = 1.25,
    alpha       = 0.75,
    inherit.aes = FALSE
  ) +
  geom_point(stat = "identity", size = 4, fill = "white") +
  scale_shape_manual(values = c(21, 25, 22)) +
  scale_color_brewer(type = "qual", palette = 7) +
  scale_x_continuous(
    breaks = 0:3,
    labels = c("Pre-treat\n-ment", "Week 1", "Week 2", "Week 3")
  ) +
  scale_y_continuous(
    limits = c(-2, 105),
    breaks = c(0, 25, 50, 75, 100),
    labels = c(100, 75, 50, 25, 0),
    sec.axis = sec_axis(
      trans   = ~.,
      name    = "Relative ADC Increase\nfrom Baseline (%)\n",
      breaks  = c(0, 20, 40, 60, 80, 100),
      labels  = c(0, 20, 40, 60, 80, 100) / 4
    )
  ) +
  xlab("") +
  ylab("Relative Decrease\nfrom Baseline (%)\n") +
  theme_classic() +
  theme(
    axis.title.x = element_text(margin = ggplot2::margin(t = 20)),
    axis.text.x  = element_text(margin = ggplot2::margin(t = 7), size = 12),
    axis.text.y  = element_text(size = 12)
  ) +
  guides(
    color = guide_legend(title = "Assay Modality", order = 1),
    shape = guide_legend(title = "ctDNA Status",   order = 2)
  )
```

```{r build_plots_F4de, eval = TRUE, include = FALSE}

# --- Wide tables for % reduction and ECDF ---
smry_af  <- make_wide(idx_metrics_ft, "mean_af",       "AF")
smry_hpv <- make_wide(
  dplyr::filter(idx_metrics_ft, hpv_type_wes_wgs == "HPV-16"),
  "aligned_reads", "HPV"
)
smry_mri <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    AF_wk0  = MRI_rawdata_wk0,    # one-week imaging offset
    AF_wk1  = MRI_rawdata_wk2,
    AF_wk2  = MRI_rawdata_wk3,
    AF_wk3  = MRI_rawdata_wk4
  ) %>%
  dplyr::rename(
    MRI_wk0 = AF_wk0, MRI_wk1 = AF_wk1, MRI_wk2 = AF_wk2, MRI_wk3 = AF_wk3
  ) %>%
  readr::type_convert()

# Relative change from baseline
smry_af_rel <- smry_af %>%
  dplyr::mutate(
    wk1 = AF_wk1 / AF_wk0, wk2 = AF_wk2 / AF_wk0,
    wk3 = AF_wk3 / AF_wk0, `Pre-treatment` = 0
  ) %>%
  dplyr::select(patient_id_mskcc, `Pre-treatment`, wk1, wk2, wk3)

smry_hpv_rel <- smry_hpv %>%
  dplyr::mutate(
    wk1 = HPV_wk1 / HPV_wk0, wk2 = HPV_wk2 / HPV_wk0,
    wk3 = HPV_wk3 / HPV_wk0, `Pre-treatment` = 0
  ) %>%
  dplyr::select(patient_id_mskcc, `Pre-treatment`, wk1, wk2, wk3)

smry_mri_rel <- smry_mri %>%
  dplyr::mutate(
    wk1 = MRI_wk1 / MRI_wk0, wk2 = MRI_wk2 / MRI_wk0,
    wk3 = MRI_wk3 / MRI_wk0, `Pre-treatment` = 0
  ) %>%
  dplyr::select(patient_id_mskcc, `Pre-treatment`, wk1, wk2, wk3)

# --- F4d: fraction achieving ≥30% and ≥90% reduction ---
plot_pct_reduction <- smry_af_rel %>%
  reshape2::melt(value.name = "PCM", variable.name = "week") %>%
  dplyr::full_join(
    reshape2::melt(smry_hpv_rel, value.name = "HPV",  variable.name = "week"),
    by = c("patient_id_mskcc", "week")
  ) %>%
  dplyr::full_join(
    reshape2::melt(smry_mri_rel, value.name = "MRI", variable.name = "week"),
    by = c("patient_id_mskcc", "week")
  ) %>%
  readr::type_convert() %>%
  dplyr::filter(week != "Pre-treatment") %>%
  dplyr::group_by(week) %>%
  dplyr::summarize(
    `30_%_pcm` = 100 * sum(PCM <= 0.7, na.rm = TRUE) / sum(!is.na(PCM)),
    `30_%_hpv` = 100 * sum(HPV <= 0.7, na.rm = TRUE) / sum(!is.na(HPV)),
    `30_%_mri` = 100 * sum(MRI <= 0.7, na.rm = TRUE) / sum(!is.na(MRI)),
    `90_%_pcm` = 100 * sum(PCM <= 0.1, na.rm = TRUE) / sum(!is.na(PCM)),
    `90_%_hpv` = 100 * sum(HPV <= 0.1, na.rm = TRUE) / sum(!is.na(HPV)),
    `90_%_mri` = 100 * sum(MRI <= 0.1, na.rm = TRUE) / sum(!is.na(MRI)),
    .groups = "drop"
  ) %>%
  reshape2::melt(value.name = "%", variable.name = "assay") %>%
  dplyr::mutate(
    `%_reduction` = dplyr::case_when(
      grepl("30_%", assay, fixed = TRUE) ~ "30%",
      grepl("90_%", assay, fixed = TRUE) ~ "90%"
    ),
    assay = toupper(gsub("30_%_|90_%_", "", assay, perl = TRUE)),
    week  = gsub("wk", "", week, fixed = TRUE)
  ) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    assay         = factor(assay,         levels = c("PCM", "HPV", "MRI"), ordered = TRUE),
    `%_reduction` = factor(`%_reduction`, levels = c("30%", "90%"),        ordered = TRUE)
  ) %>%
  ggplot(aes(x = week, y = `%`, color = assay, shape = assay, linetype = `%_reduction`)) +
  geom_line(stat = "identity", linewidth = 0.75, alpha = 0.95) +
  geom_point(stat = "identity", fill = "white", size = 3) +
  scale_shape_manual(values = c(21, 25, 22)) +
  scale_color_brewer(type = "qual", palette = 7) +
  scale_linetype_manual(values = c(1, 3)) +
  scale_x_continuous(
    expand = c(0.1, 0.1),
    breaks = 1:3,
    labels = c("1", "2", "3")
  ) +
  scale_y_continuous(
    limits = c(0, 100),
    breaks = c(0, 25, 50, 75, 100),
    labels = c(0, 25, 50, 75, 100)
  ) +
  xlab("Weeks") +
  ylab("Fraction of Patients (%)") +
  theme_classic() +
  theme(
    axis.title.x = element_text(margin = ggplot2::margin(t = 20)),
    axis.title.y = element_text(margin = ggplot2::margin(r = 20)),
    axis.text.x  = element_text(margin = ggplot2::margin(t = 7), size = 12),
    axis.text.y  = element_text(size = 12),
    strip.background = element_blank()
  ) +
  guides(
    color    = guide_legend(title = "Assay Modality"),
    shape    = guide_legend(title = "Assay Modality"),
    linetype = guide_legend(title = "Baseline\nReduction")
  )

# --- F4e: empirical CDF of relative change at week 2 ---
ecdf_mri <- smry_mri_rel %>%
  dplyr::select(patient_id_mskcc, wk2) %>%
  tidyr::drop_na() %>%
  dplyr::mutate(relative_change = log10(wk2)) %>%
  dplyr::arrange(relative_change) %>%
  .[["relative_change"]] %>%
  ecdf()

ecdf_pcm <- smry_af_rel %>%
  dplyr::select(patient_id_mskcc, wk2) %>%
  tidyr::drop_na() %>%
  dplyr::mutate(relative_change = log10(wk2)) %>%
  dplyr::arrange(relative_change) %>%
  .[["relative_change"]] %>%
  ecdf()

plot_ecdf <- dplyr::bind_rows(
  dplyr::tibble(relative_change = knots(ecdf_mri)) %>%
    dplyr::mutate(`%` = ecdf_mri(relative_change), assay = "MRI"),
  dplyr::tibble(relative_change = knots(ecdf_pcm)) %>%
    dplyr::mutate(`%` = ecdf_pcm(relative_change), assay = "PCM")
) %>%
  ggplot(aes(x = `%`, y = relative_change, color = assay)) +
  geom_segment(aes(x = `%`, xend = `%`, y = 0, yend = relative_change)) +
  geom_hline(yintercept = 0, color = "#bdbdbd", alpha = 1, linewidth = 0.75) +
  geom_vline(
    data    = dplyr::tibble(xintercept = c(0.03, 0.03 + 0.68), assay = c("MRI", "MRI")),
    mapping = aes(xintercept = xintercept),
    linetype = 3
  ) +
  geom_vline(
    data    = dplyr::tibble(xintercept = c(0.33, 0.33 + 0.19, 0.33 + 0.19 + 0.19), assay = rep("PCM", 3)),
    mapping = aes(xintercept = xintercept),
    linetype = 3
  ) +
  geom_point(stat = "identity", size = 1, shape = 21, fill = "white") +
  scale_color_manual(values = c("PCM" = "#1b9e77", "MRI" = "#7570b3")) +
  scale_x_reverse() +
  scale_y_continuous(limits = c(NA, 1)) +
  xlab(" ") +
  ylab(expression("Relative Change " (Log[10]))) +
  theme_classic() +
  theme(
    axis.title.x  = element_text(margin = ggplot2::margin(t = 20)),
    axis.text.x   = element_blank(),
    axis.ticks.x  = element_blank(),
    axis.line.x   = element_blank(),
    axis.title.y  = element_text(margin = ggplot2::margin(r = 20)),
    axis.text.y   = element_text(size = 12),
    strip.background = element_blank(),
    strip.text    = element_text(color = "white")
  ) +
  facet_wrap(~assay, nrow = 2, ncol = 1, scales = "free_y") +
  guides(color = guide_legend(title = "Assay Modality"))
```

```{r build_plot_F4f, eval = TRUE, include = FALSE}

# --- Correlation pivot tables ---
smry_pcm <- idx_metrics_ft %>%
  dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(mean_af = mean(mean_af + 1e-5, na.rm = TRUE), .groups = "drop") %>%
  reshape2::dcast(
    formula       = patient_id_mskcc ~ timepoint_weeks_since_start_of_RT,
    fun.aggregate = function(x) mean(x, na.rm = TRUE),
    fill          = NaN,
    value.var     = "mean_af"
  ) %>%
  dplyr::select(patient_id_mskcc, `Pre-treatment`, wk1, wk2, wk3) %>%
  readr::type_convert()

smry_hpv_wide <- idx_metrics_ft %>%
  dplyr::filter(chromosome == "HPV-16") %>%
  dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(aligned_reads = mean(aligned_reads + 1, na.rm = TRUE), .groups = "drop") %>%
  reshape2::dcast(
    formula       = patient_id_mskcc ~ timepoint_weeks_since_start_of_RT,
    fun.aggregate = function(x) mean(x, na.rm = TRUE),
    fill          = NaN,
    value.var     = "aligned_reads"
  ) %>%
  dplyr::select(patient_id_mskcc, `Pre-treatment`, wk1, wk2, wk3) %>%
  readr::type_convert()

smry_mri_wide <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    `Pre-treatment` = MRI_rawdata_wk0,
    wk1 = MRI_rawdata_wk2,   # one-week imaging offset
    wk2 = MRI_rawdata_wk3,
    wk3 = MRI_rawdata_wk4
  ) %>%
  readr::type_convert()

# --- Helper: shared scatter + smooth + stat_cor structure ---
corr_scatter <- function(df, x_col, y_col, x_scale, y_scale, x_lab, y_lab,
                         cor_x, cor_y) {
  df %>%
    dplyr::filter(week != "Pre-treatment") %>%
    dplyr::mutate(week = gsub("wk", "Week ", week, fixed = TRUE)) %>%
    ggplot(aes(x = .data[[x_col]], y = .data[[y_col]], shape = week, color = week)) +
    geom_point(stat = "identity", fill = "white", alpha = 1, size = 2) +
    geom_smooth(
      stat = "smooth", method = "rlm", formula = y ~ x,
      se = FALSE, fullrange = TRUE, color = "goldenrod3", linewidth = 0.85
    ) +
    scale_color_brewer(type = "qual", palette = 7) +
    scale_shape_manual(values = c(21, 22, 23, 24)) +
    x_scale +
    y_scale +
    xlab(x_lab) +
    ylab(y_lab) +
    ggpubr::stat_cor(method = "spearman", color = "black", label.x = cor_x, label.y = cor_y) +
    theme_classic() +
    theme(
      axis.title.x     = element_text(margin = ggplot2::margin(t = 20), size = 12),
      axis.title.y     = element_text(margin = ggplot2::margin(r = 20), size = 12),
      axis.text.x      = element_text(size = 10),
      axis.text.y      = element_text(size = 10),
      strip.background = element_blank()
    ) +
    facet_wrap(~week, nrow = 1, scales = "free_y") +
    guides(color = "none", shape = "none")
}

# F4f top: ctDNA fraction vs HPV aligned reads
plot_ctdna_chpv <- smry_pcm %>%
  reshape2::melt(variable.name = "week", value.name = "AF") %>%
  dplyr::full_join(
    reshape2::melt(smry_hpv_wide, variable.name = "week", value.name = "HPV"),
    by = c("patient_id_mskcc", "week")
  ) %>%
  tidyr::drop_na() %>%
  corr_scatter(
    x_col   = "AF",
    y_col   = "HPV",
    x_scale = scale_x_log10(labels = scientific_10),
    y_scale = scale_y_log10(limits = c(1e0, 1e7), breaks = c(1e0, 1e2, 1e4, 1e6), labels = scientific_10),
    x_lab   = "",
    y_lab   = "cfDNA HPV Aligned Read Pairs",
    cor_x   = log10(1e-5),
    cor_y   = log10(5e6)
  )

# F4f bottom: ctDNA fraction vs MRI volume
plot_ctdna_mri <- smry_pcm %>%
  reshape2::melt(variable.name = "week", value.name = "AF") %>%
  dplyr::full_join(
    reshape2::melt(smry_mri_wide, variable.name = "week", value.name = "MRI"),
    by = c("patient_id_mskcc", "week")
  ) %>%
  tidyr::drop_na() %>%
  dplyr::mutate(MRI = MRI / 1000) %>%
  corr_scatter(
    x_col   = "AF",
    y_col   = "MRI",
    x_scale = scale_x_log10(labels = scientific_10),
    y_scale = scale_y_log10(limits = c(1e3, 7e4) / 1000, labels = scientific_10),
    x_lab   = "ctDNA Fraction (%)",
    y_lab   = expression("MRI Volume " (cm^3)),
    cor_x   = log10(1e-5),
    cor_y   = log10(6e4 / 1000)
  )
```

```{r build_plot_F4g, eval = TRUE, include = FALSE}

# --- Marginal detection rates per week per assay ---
mrd_base <- make_mrd_detect()

smry__mrd <- mrd_base %>%
  dplyr::group_by(timepoint_weeks_since_start_of_RT, patient_id_mskcc) %>%
  dplyr::summarize(Is_ctDNA = any(`MRD-Landmark_Result` == "PRESENT"), .groups = "drop") %>%
  dplyr::group_by(timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(N = n(), `Is_ctDNA_%` = 100 * sum(Is_ctDNA) / n(), .groups = "drop")

smry__hpv <- posterior_probs %>%
  dplyr::group_by(timepoint_weeks_since_start_of_RT, patient_id_mskcc) %>%
  dplyr::summarize(Is_ctDNA = any(Is_ctDNA == "+ve"), .groups = "drop") %>%
  dplyr::group_by(timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(N = n(), `Is_ctDNA_%` = 100 * sum(Is_ctDNA) / n(), .groups = "drop")

smry__mrd_hpv <- mrd_base %>%
  dplyr::left_join(
    dplyr::select(posterior_probs, sample_name, Is_ctDNA__HPV = Is_ctDNA),
    by = "sample_name"
  ) %>%
  dplyr::group_by(timepoint_weeks_since_start_of_RT, patient_id_mskcc) %>%
  dplyr::summarize(
    Is_ctDNA_MRD = any(`MRD-Landmark_Result` == "PRESENT"),
    Is_ctDNA_HPV = any(Is_ctDNA__HPV == "+ve"),
    .groups = "drop"
  ) %>%
  dplyr::group_by(timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(
    N = n(),
    `Is_ctDNA_%` = 100 * sum(Is_ctDNA_MRD | Is_ctDNA_HPV) / n(),
    .groups = "drop"
  )

plot_detect_rate_bar <- smry__mrd %>%
  dplyr::rename(PCM = `Is_ctDNA_%`) %>%
  dplyr::left_join(dplyr::rename(smry__hpv,     HPV      = `Is_ctDNA_%`),
                   by = c("timepoint_weeks_since_start_of_RT", "N")) %>%
  dplyr::left_join(dplyr::rename(smry__mrd_hpv, Combined = `Is_ctDNA_%`),
                   by = c("timepoint_weeks_since_start_of_RT", "N")) %>%
  reshape2::melt() %>%
  dplyr::filter(
    variable != "N",
    timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3", "wk5")
  ) %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = gsub("wk", "Week ", timepoint_weeks_since_start_of_RT, fixed = TRUE)
  ) %>%
  ggplot(aes(x = timepoint_weeks_since_start_of_RT, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge", color = "white", width = 0.75) +
  scale_fill_brewer(type = "qual", palette = 7) +
  xlab("") +
  ylab("Fraction of Patients (%)") +
  scale_x_discrete() +
  scale_y_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, by = 10),
    labels = c(0, "", 20, "", 40, "", 60, "", 80, "", 100)
  ) +
  theme_classic() +
  theme(
    axis.title.x = element_text(margin = ggplot2::margin(t = 20), size = 12),
    axis.title.y = element_text(margin = ggplot2::margin(r = 20), size = 12),
    axis.text.x  = element_text(size = 12, angle = 90, vjust = 0.5, hjust = 1),
    axis.text.y  = element_text(size = 12)
  ) +
  guides(fill = guide_legend(title = "Assay"))

# --- Cross-tab: HPV vs MRD per week ---
smry__crosstab <- mrd_base %>%
  dplyr::group_by(timepoint_weeks_since_start_of_RT, patient_id_mskcc) %>%
  dplyr::summarize(MRD = any(`MRD-Landmark_Result` == "PRESENT"), .groups = "drop") %>%
  dplyr::full_join(
    posterior_probs %>%
      dplyr::group_by(timepoint_weeks_since_start_of_RT, patient_id_mskcc) %>%
      dplyr::summarize(HPV = any(Is_ctDNA == "+ve"), .groups = "drop"),
    by = c("timepoint_weeks_since_start_of_RT", "patient_id_mskcc")
  ) %>%
  dplyr::filter(
    timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3", "wk5")
  ) %>%
  dplyr::group_by(timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(
    TP = sum( MRD &  HPV, na.rm = TRUE),
    FP = sum(!MRD &  HPV, na.rm = TRUE),
    FN = sum( MRD & !HPV, na.rm = TRUE),
    TN = sum(!MRD & !HPV, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  reshape2::melt() %>%
  reshape2::dcast(variable ~ timepoint_weeks_since_start_of_RT, value.var = "value") %>%
  dplyr::select(-variable) %>%
  as.list() %>%
  lapply(function(x) {
    y <- matrix(x, 2, 2, byrow = TRUE)
    rownames(y) <- colnames(y) <- c("+ve", "-ve")
    y
  })
```

<br/>
<br/>

```{r plot_byweek, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3, fig.width = 12, fig.cap = '<br/>**Figure 4a** Density plots of imaging (T2 MRI volume and DW MRI mean ADC) and genomic (ctDNA fraction inferred from PCM and number of cfDNA aligned HPV-16 read pairs) biomarkers across weekly measurements.'}

suppressWarnings(grid.arrange(plot_mri, plot_adc, plot_ctdna, plot_chpv, nrow = 1, ncol = 4, widths = c(1.35, 1, 1, 1)))
```

<br/>
<br/>

```{r plot_ctms161, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3, fig.width = 6, fig.cap = '<br/>**Figure 4c** ctDNA dynamic tracking showing the percentage change of imaging and genomic measures from baseline across weeks 1 to 3 from patient CTMS-161.'}

print(plot_ctms161)
```

<br/>
<br/>

```{r plot_pct_reduction, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3, fig.width = 4, fig.cap = '<br/>**Figure 4d** Proportion of patients achieving clinically relevant response thresholds (>30% reduction, solid line; >90% reduction, dotted line) by modality (MRI, PCM, HPV) across treatment timepoints, highlighting earlier response detection with PCM or HPV assays.'}

print(plot_pct_reduction)
```

<br/>
<br/>

```{r plot_ecdf, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3, fig.width = 5, fig.cap = '<br/>**Figure 4e** Waterfall plots comparing the magnitude of change in tumor volume (top) versus ctDNA fraction (bottom) at week 2 on-treatment.'}

print(plot_ecdf)
```

<br/>
<br/>

```{r plot_cor, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 5.5, fig.width = 8, fig.cap = '<br/>**Figure 4f** Correlation of ctDNA fraction with cfDNA aligned HPV-16 read pairs (top) and on-treatment MRI-derived tumor volume (bottom).'}

suppressWarnings(grid.arrange(plot_ctdna_chpv, plot_ctdna_mri, nrow = 2, ncol = 1))
```

<br/>
<br/>

```{r plot_detect, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3, fig.width = 5.5}

print(plot_detect_rate_bar)
```

```{r plot_crosstab, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 5.5, fig.cap = '<br/>**Figure 4g** Bar plot with confusion matrices displaying on-treatment ctDNA detection rates by assay type (PCM, HPV, Combined).'}

corrplot::corrplot(
  corr         = do.call(cbind, smry__crosstab),
  method       = "circle",
  type         = "full",
  col          = colorRampPalette(RColorBrewer::brewer.pal(n = 11, name = "RdBu"))(25),
  is.corr      = FALSE,
  diag         = TRUE,
  addgrid.col  = NA,
  addCoef.col  = "white",
  order        = "original",
  outline      = TRUE,
  number.cex   = 0.75,
  number.font  = 1,
  number.digits = 0,
  tl.cex       = 1,
  tl.col       = "black",
  tl.srt       = 0,
  cl.pos       = "r",
  cl.ratio     = 0.1,
  cl.length    = 7,
  cl.align.text = "l"
)
```
