---
title: "Supplementary Figure S12 - Univariate associations between assay modalities and treatment outcomes"
author:
  - name: David N Brown, Bill H Diplas
    affiliation: Memorial Sloan Kettering Cancer Center
output:
  html_document:
    theme: cerulean
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}

suppressPackageStartupMessages({
  library("ggplot2")
  library("readr")
  library("dplyr")
  library("tidyr")
  library("magrittr")
  library("reshape2")
  library("ggpubr")
  library("MASS")
  library("viridis")
})

# --- Data paths ---
url_manifest                 <- "../data/manifest.txt"
url_mrd_summary              <- "../data/TM-2021-MSK-002_MRD_Results_Summary_20220825.txt"
url_preanalytical_conditions <- "../data/pre-analytical_conditions.txt"
url_hpv_type                 <- "../data/TM-2021-MSK-002_HPV_Typing_WES_WGS.txt"
url_no_node_dissection       <- "../data/patients_0_nodal_dissection.txt"
url_clinical                 <- "../data/clinical.txt"
url_mutation_summary         <- "../data/mutation_summary.maf"
url_idx_metrics_ft           <- "../data/idx_metrics_ft.txt"
url_posterior_probs          <- "../res/Posterior_Probability_ALL.txt"

target_contigs <- c(
  "HPV-16" = "NC001526.4",
  "HPV-18" = "NC001357.1",
  "HPV-31" = "J04353.1",
  "HPV-33" = "M12732.1",
  "HPV-35" = "X74477.1"
)

FRAGMENT_LENGTH_THRESHOLD <- 37


scientific_10 <- function(x) {
  parse(text = gsub("+", "", gsub("e", " %.% 10^", scales::scientific_format()(x)), fixed = TRUE))
}
```

```{r load_shared_data, eval = TRUE, include = FALSE}


manifest_raw <- readr::read_tsv(
  url_manifest, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::filter(!is.na(bam_file_name_hpv)) %>%
  dplyr::mutate(sample_uuid = paste0(sample_id_mskcc, "-", sample_id_invitae))

preanalytical_conditions <- readr::read_tsv(
  url_preanalytical_conditions, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

mrd_smry <- readr::read_tsv(
  url_mrd_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    sample_uuid = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE),
    sample_name = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE)
  )

hpv_smry <- readr::read_tsv(
  url_hpv_type, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    patient_id_mskcc = gsub("-T", "", patient_name, fixed = TRUE),
    patient_id_mskcc = gsub("155salv", "155", patient_id_mskcc, fixed = TRUE),
    hpv_type_wes     = gsub("HPV", "HPV-", hpv_type_wes, fixed = TRUE),
    hpv_type_wgs     = gsub("HPV", "HPV-", hpv_type_wgs, fixed = TRUE),
    hpv_type_wes_wgs = gsub("HPV", "HPV-", hpv_type_wes_wgs, fixed = TRUE),
    hpv_type_wes_wgs = dplyr::coalesce(hpv_type_wes_wgs, "Unknown")
  )

nodal_dissection_smry <- readr::read_tsv(
  url_no_node_dissection, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(patient_id_mskcc = sample)

manifest <- manifest_raw %>%
  dplyr::left_join(preanalytical_conditions, by = "sample_id_mskcc") %>%
  dplyr::mutate(
    patient_id_mskcc = dplyr::case_when(
      is.na(patient_id_mskcc) & sample_id_mskcc == "21-144-03654" ~ "CTMS-164",
      TRUE ~ patient_id_mskcc
    ),
    sample_name = paste0(sample_id_mskcc, "-", sample_id_invitae)
  ) %>%
  dplyr::left_join(hpv_smry, by = "patient_id_mskcc")

primer_set = readr::read_tsv(file = url_primers, col_names = FALSE, col_types = cols(.default = col_character())) %>%
		     readr::type_convert() %>%
		     dplyr::mutate(insert_size = X3 - X2)

mutation_smry <- readr::read_tsv(
  url_mutation_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

clinical <- readr::read_tsv(
  url_clinical, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

posterior_probs <- readr::read_tsv(
  url_posterior_probs, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = floor(timepoint_days_since_start_of_RT / 7),
    timepoint_weeks_since_start_of_RT = dplyr::case_when(
      timepoint_weeks_since_start_of_RT < 0 ~ "Pre-treatment",
      TRUE ~ paste0("wk", timepoint_weeks_since_start_of_RT)
    )
  )

idx_metrics_ft <- readr::read_tsv(
  url_idx_metrics_ft, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::select(
    sample_name		= SAMPLE_NAME,
    contig			= CHROMOSOME,
    aligned_reads	= ALIGNED_READS,
    fragment_length	= FRAGMENT_LENGTH
  ) %>%
  dplyr::left_join(
    dplyr::tibble(contig = target_contigs, chromosome = names(target_contigs)),
    by = "contig"
  ) %>%
  dplyr::filter(fragment_length == FRAGMENT_LENGTH_THRESHOLD, !is.na(chromosome)) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::left_join(
    clinical %>%
    dplyr::select(patient_id_mskcc, hpv_type_panel),
    by = "patient_id_mskcc"
  ) %>%
  dplyr::mutate(hpv_type_panel = gsub(pattern = "HPV", replacement = "HPV-", x = hpv_type_panel, fixed = TRUE)) %>%
  dplyr::mutate(hpv_type_wes_wgs_panel = case_when(
      hpv_type_wes_wgs == "Unknown" ~ hpv_type_panel,
      TRUE ~ hpv_type_wes_wgs
    )
  ) %>%
  dplyr::mutate(hpv_type_wes_wgs_panel = case_when(
      is.na(hpv_type_wes_wgs_panel) ~ "Unknown",
      TRUE ~ hpv_type_wes_wgs_panel
    )
  ) %>%
  dplyr::filter(chromosome == hpv_type_wes_wgs_panel) %>%
  dplyr::left_join(
    mutation_smry %>%
    dplyr::filter(FILTER == "PASS") %>%
    dplyr::group_by(Tumor_Sample_Barcode) %>%
    dplyr::summarize(mean_af = mean(t_maf)) %>%
    dplyr::ungroup() %>%
    dplyr::rename(sample_name = Tumor_Sample_Barcode),
    by = "sample_name"
  ) %>%
  dplyr::mutate(timepoint_weeks_since_start_of_RT = floor(timepoint_days_since_start_of_RT/7)) %>%
  dplyr::mutate(timepoint_weeks_since_start_of_RT = case_when(
      timepoint_weeks_since_start_of_RT < 0 ~ "Pre-treatment",
      TRUE ~ paste0("wk", timepoint_weeks_since_start_of_RT)
    )
  )
			
smry_ <- idx_metrics_ft %>%
  dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(mean_af = mean(mean_af+(1e-5), na.rm = TRUE)) %>%
  reshape2::dcast(formula = patient_id_mskcc ~ timepoint_weeks_since_start_of_RT,
    fun.aggregate = function(x) { mean(x, na.rm=TRUE) }, fill = NaN, value.var = "mean_af") %>%
  dplyr::select(patient_id_mskcc, `Pre-treatment`, wk1, wk2, wk3) %>%
  dplyr::mutate(
    rel_AF_wk1 = wk1/`Pre-treatment`,
    rel_AF_wk2 = wk2/`Pre-treatment`,
    rel_AF_wk3 = wk3/`Pre-treatment`
  ) %>%
  dplyr::rename(
    abs_AF_wk0 = `Pre-treatment`,
    abs_AF_wk1 = wk1,
    abs_AF_wk2 = wk2,
    abs_AF_wk3 = wk3
  ) %>%
  dplyr::full_join(
    idx_metrics_ft %>%
    dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
    dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
    dplyr::summarize(aligned_reads = mean(aligned_reads)) %>%
    reshape2::dcast(formula = patient_id_mskcc ~ timepoint_weeks_since_start_of_RT,
      fun.aggregate = function(x) { mean(x, na.rm=TRUE) }, fill = NaN, value.var = "aligned_reads") %>%
    dplyr::select(patient_id_mskcc, `Pre-treatment`, wk1, wk2, wk3) %>%
    dplyr::mutate(
      rel_HPV_wk1 = wk1/`Pre-treatment`,
      rel_HPV_wk2 = wk2/`Pre-treatment`,
      rel_HPV_wk3 = wk3/`Pre-treatment`
    ) %>%
    dplyr::rename(
      abs_HPV_wk0 = `Pre-treatment`,
      abs_HPV_wk1 = wk1,
      abs_HPV_wk2 = wk2,
      abs_HPV_wk3 = wk3
    ),
    by = "patient_id_mskcc") %>%
  dplyr::full_join(clinical, by = "patient_id_mskcc") %>%
  dplyr::select(
    patient_id_mskcc,
    composite_end_point,
    neck_dissection_yes_no,
    hypoxia_resolution,
    abs_AF_wk0, abs_AF_wk1, abs_AF_wk2, abs_AF_wk3,
    rel_AF_wk1, rel_AF_wk2, rel_AF_wk3,
    abs_HPV_wk0, abs_HPV_wk1, abs_HPV_wk2, abs_HPV_wk3,
    rel_HPV_wk1, rel_HPV_wk2, rel_HPV_wk3,
    abs_MRI_wk0 = MRI_rawdata_wk0,
    abs_MRI_wk1 = MRI_rawdata_wk2,
    abs_MRI_wk2 = MRI_rawdata_wk3,
    abs_MRI_wk3 = MRI_rawdata_wk4) %>%
  dplyr::mutate(
    rel_MRI_wk1 = (abs_MRI_wk1/abs_MRI_wk0),
    rel_MRI_wk2 = (abs_MRI_wk2/abs_MRI_wk0),
    rel_MRI_wk3 = (abs_MRI_wk3/abs_MRI_wk0)
  ) %>%
  dplyr::mutate(
    composite_end_point = case_when(
      composite_end_point ~ 1,
      !composite_end_point ~ 0
    )
  ) %>%
  dplyr::mutate(
    neck_dissection_yes_no = case_when(
      neck_dissection_yes_no == "yes" ~ "1",
      neck_dissection_yes_no == "no" ~ "0"
    )
  ) %>%
  dplyr::mutate(
    hypoxia_resolution = case_when(
      hypoxia_resolution == "persistent" ~ "1",
      hypoxia_resolution == "resolved" ~ "0"
    )
  ) %>%
  readr::type_convert() %>%
  dplyr::select(-patient_id_mskcc) %>%
  reshape2::melt(id.vars = c("composite_end_point", "neck_dissection_yes_no", "hypoxia_resolution")) %>%
  tidyr::drop_na()

uvars = unique(smry_$variable)

p1 = vector(mode = "numeric", length = length(uvars))
for (i in 1:length(uvars)) {
	p1[i] = (smry_ %>%
			dplyr::filter(variable == uvars[i]) %>%
			dplyr::mutate(value = log2(value)) %>%
			stats::glm(formula = composite_end_point ~ value, data = ., family = binomial(link = "probit")) %>%
			summary() %>%
			.[["coefficients"]])[2,"Pr(>|z|)"]
}

p2 = vector(mode = "numeric", length = length(uvars))
for (i in 1:length(uvars)) {
	p2[i] = (smry_ %>%
			dplyr::filter(variable == uvars[i]) %>%
			dplyr::mutate(value = log2(value)) %>%
			stats::glm(formula = neck_dissection_yes_no ~ value, data = ., family = binomial(link = "probit")) %>%
			summary() %>%
			.[["coefficients"]])[2,"Pr(>|z|)"]
}

p3 = vector(mode = "numeric", length = length(uvars))
for (i in 1:length(uvars)) {
	p3[i] = (smry_ %>%
			dplyr::filter(variable == uvars[i]) %>%
			dplyr::mutate(value = log2(value)) %>%
			stats::glm(formula = hypoxia_resolution ~ value, data = ., family = binomial(link = "probit")) %>%
			summary() %>%
			.[["coefficients"]])[2,"Pr(>|z|)"]
}

q1 = vector(mode = "numeric", length = length(uvars))
for (i in 1:length(uvars)) {
	q1[i] = smry_ %>%
			dplyr::filter(variable == uvars[i]) %>%
			wilcox.test(formula = value ~ composite_end_point, data = ., exact = FALSE) %>%
			.[["p.value"]]
}

q2 = vector(mode = "numeric", length = length(uvars))
for (i in 1:length(uvars)) {
	q2[i] = smry_ %>%
			dplyr::filter(variable == uvars[i]) %>%
			wilcox.test(formula = value ~ neck_dissection_yes_no, data = ., exact = FALSE) %>%
			.[["p.value"]]
}

q3 = vector(mode = "numeric", length = length(uvars))
for (i in 1:length(uvars)) {
	q3[i] = smry_ %>%
			dplyr::filter(variable == uvars[i]) %>%
			wilcox.test(formula = value ~ hypoxia_resolution, data = ., exact = FALSE) %>%
			.[["p.value"]]
}

res_ = dplyr::tibble(variables = uvars,
				     `De-escalation failure` = p2,
				     `PET response` = p3,
				     `Risk group` = p1) %>%
       dplyr::mutate(Method = "log") %>%
       dplyr::bind_rows(dplyr::tibble(variables = uvars,
					    `De-escalation failure` = q2,
					    `PET response` = q3,
				        `Risk group` = q1) %>%
						dplyr::mutate(Method = "u")) %>%
       dplyr::add_row(`variables` = "rel_AF_wk0",
				      `De-escalation failure` = 1,
				      `PET response` = 1,
				      `Risk group` = 1,
				      Method = "log") %>%
       dplyr::add_row(`variables` = "rel_MRI_wk0",
				      `De-escalation failure` = 1,
				      `PET response` = 1,
				      `Risk group` = 1,
				      Method = "log") %>%
       dplyr::add_row(`variables` = "rel_HPV_wk0",
				      `De-escalation failure` = 1,
				      `PET response` = 1,
				      `Risk group` = 1,
				      Method = "log") %>%
       dplyr::add_row(`variables` = "rel_AF_wk0",
				      `De-escalation failure` = 1,
				      `PET response` = 1,
				      `Risk group` = 1,
				      Method = "u") %>%
       dplyr::add_row(`variables` = "rel_MRI_wk0",
				      `De-escalation failure` = 1,
				      `PET response` = 1,
				      `Risk group` = 1,
				      Method = "u") %>%
       dplyr::add_row(`variables` = "rel_HPV_wk0",
				      `De-escalation failure` = 1,
				      `PET response` = 1,
				      `Risk group` = 1,
				      Method = "u")

plot_ = res_ %>%
		dplyr::filter(Method == "log") %>%
		dplyr::select(-Method) %>%
		reshape2::melt() %>%
		dplyr::mutate(value = p.adjust(value, method = "BH")) %>%
		dplyr::mutate(value = -log10(value)) %>%
		dplyr::mutate(week = case_when(
						grepl("wk0", variables, fixed = TRUE) ~ "Pre-treat\n-ment",
						grepl("wk1", variables, fixed = TRUE) ~ "Week 1",
						grepl("wk2", variables, fixed = TRUE) ~ "Week 2",
						grepl("wk3", variables, fixed = TRUE) ~ "Week 3"
		)) %>%
		dplyr::mutate(assay = case_when(
						grepl("AF", variables, fixed = TRUE) ~ "PCM",
						grepl("HPV", variables, fixed = TRUE) ~ "HPV",
						grepl("MRI", variables, fixed = TRUE) ~ "MRI"
		)) %>%
		dplyr::mutate(mode = case_when(
						grepl("rel", variables, fixed = TRUE) ~ "Relative",
						grepl("abs", variables, fixed = TRUE) ~ "Absolute",
		)) %>%
		dplyr::select(-variables) %>%
		dplyr::mutate(mode = factor(mode, levels = c("Absolute", "Relative"), ordered = TRUE)) %>%
		dplyr::mutate(assay = factor(assay, levels = c("HPV", "PCM", "MRI"), ordered = TRUE)) %>%
		dplyr::mutate(variable = factor(variable, levels = c("Risk group", "PET response", "De-escalation failure"), ordered = TRUE)) %>%
		ggplot(aes(x = week, y = variable, fill = value, label = signif(10^(-1*value), 2))) +
		geom_tile(stat = "identity", color = "white", size = .5) +
		geom_text(color = "white", size = 2) +
		scale_fill_viridis(breaks = seq(from = 0, to = 1.45, by = .35)) +
		xlab("") +
		ylab("") +
		theme_minimal() +
		theme(axis.title.x = element_text(margin = margin(t = 20), size = 12),
		      axis.title.y = element_text(margin = margin(r = 20), size = 12),
		      axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1),
		      axis.text.y = element_text(size = 12),
		      strip.background = element_blank()) +
		facet_grid(mode~assay) +
		guides(fill = guide_colourbar(title = expression(-Log[10](q))))
```		

```{r plot_univariate_heatmap, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 5/1.25, fig.width = 10/1.2, fig.cap = '<br/>**Supplementary Figure S12** Heatmap of univariate associations between assay modalities and treatment outcomes.'}

print(plot_)
```
