---
title: "Supplementary Figure S3 - Principal component analysis (PCA) of circulating HPV-16 readouts"
author:
  - name: David N Brown, Bill H Diplas
    affiliation: Memorial Sloan Kettering Cancer Center
output:
  html_document:
    theme: cerulean
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
suppressPackageStartupMessages({
  library("ggplot2")
  library("readr")
  library("dplyr")
  library("tidyr")
  library("magrittr")
  library("reshape2")
  library("MASS")
  library("broom")
})

# --- Data paths ---
url_manifest               <- "../data/manifest.txt"
url_mrd_summary            <- "../data/TM-2021-MSK-002_MRD_Results_Summary_20220825.txt"
url_preanalytical_conditions <- "../data/pre-analytical_conditions.txt"
url_hpv_type               <- "../data/TM-2021-MSK-002_HPV_Typing_WES_WGS.txt"
url_no_node_dissection     <- "../data/patients_0_nodal_dissection.txt"
url_mutation_summary       <- "../data/mutation_summary.maf"
url_insert_metrics_by_gene <- "../data/insert_metrics_by_gene.txt"
url_bed_file               <- "../data/hpv_31_33_35H_16_18.bed"

target_contigs <- c(
  "HPV-16" = "NC001526.4",
  "HPV-18" = "NC001357.1",
  "HPV-31" = "J04353.1",
  "HPV-33" = "M12732.1",
  "HPV-35" = "X74477.1"
)

# Accession → HPV type label lookup (used in smry_ pipeline)
contig_to_hpv <- c(
  "J04353.1"   = "HPV-31",
  "M12732.1"   = "HPV-33",
  "NC001357.1" = "HPV-18",
  "NC001526.4" = "HPV-16",
  "X74477.1"   = "HPV-35"
)

target_names <- c(
  "E1_1:1950", "E2_1891:2989", "E5_2985:3237",
  "E6_7124:7601", "E7_7603:7900", "L1_4774:6292"
)

# Simulation grid resolution
N_TILES <- 250
```

```{r load_shared_data, eval = TRUE, include = FALSE}

manifest_raw <- readr::read_tsv(
  url_manifest, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::filter(!is.na(bam_file_name_hpv)) %>%
  dplyr::mutate(sample_uuid = paste0(sample_id_mskcc, "-", sample_id_invitae))

preanalytical_conditions <- readr::read_tsv(
  url_preanalytical_conditions, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

mrd_smry <- readr::read_tsv(
  url_mrd_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    sample_name = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE)
  )

hpv_smry <- readr::read_tsv(
  url_hpv_type, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    patient_id_mskcc = gsub("-T", "", patient_name, fixed = TRUE),
    patient_id_mskcc = gsub("155salv", "155", patient_id_mskcc, fixed = TRUE),
    hpv_type_wes     = gsub("HPV", "HPV-", hpv_type_wes, fixed = TRUE),
    hpv_type_wgs     = gsub("HPV", "HPV-", hpv_type_wgs, fixed = TRUE),
    hpv_type_wes_wgs = gsub("HPV", "HPV-", hpv_type_wes_wgs, fixed = TRUE),
    hpv_type_wes_wgs = dplyr::coalesce(hpv_type_wes_wgs, "Unknown")
  )

nodal_dissection_smry <- readr::read_tsv(
  url_no_node_dissection, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(patient_id_mskcc = sample)

manifest <- manifest_raw %>%
  dplyr::left_join(preanalytical_conditions, by = "sample_id_mskcc") %>%
  dplyr::mutate(
    patient_id_mskcc = dplyr::case_when(
      is.na(patient_id_mskcc) & sample_id_mskcc == "21-144-03654" ~ "CTMS-164",
      TRUE ~ patient_id_mskcc
    ),
    sample_name = paste0(sample_id_mskcc, "-", sample_id_invitae)
  ) %>%
  dplyr::left_join(hpv_smry, by = "patient_id_mskcc")

mutation_smry <- readr::read_tsv(
  url_mutation_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

bed_file <- readr::read_tsv(
  url_bed_file, col_names = FALSE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(chromosome = X1, start = X2, end = X3, gene_name = X4) %>%
  dplyr::select(-X5) %>%
  dplyr::filter(gene_name != "E1^E4")

insert_size_metrics <- readr::read_tsv(
  url_insert_metrics_by_gene, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(sample_name = SAMPLE_NAME) %>%
  dplyr::filter(TARGET_REGION != "NC001526.4:3372-4794")

# --- ctDNA-positive training set ---
smry_t_pos <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(mean_af = mean(t_maf), .groups = "drop") %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode) %>%
  dplyr::filter(mean_af > 0.05) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::filter(hpv_type_wes_wgs %in% names(target_contigs)) %>%
  dplyr::left_join(
    dplyr::select(mrd_smry, sample_name, `MRD-Landmark_Result`),
    by = "sample_name"
  ) %>%
  dplyr::filter(`MRD-Landmark_Result` == "PRESENT") %>%
  dplyr::mutate(Is_ctDNA = "+ve")

# --- ctDNA-negative training set ---
neg_candidates <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(mean_af = mean(t_maf), max_af = max(t_maf), .groups = "drop") %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode) %>%
  dplyr::filter(mean_af < 0.0001, max_af < 0.001) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::left_join(nodal_dissection_smry, by = "patient_id_mskcc") %>%
  dplyr::filter(nd_event == 0, timepoint_days_since_start_of_RT > 730)

latest_per_patient <- neg_candidates %>%
  dplyr::group_by(patient_id_mskcc) %>%
  dplyr::summarize(
    timepoint_days_since_start_of_RT = max(timepoint_days_since_start_of_RT),
    .groups = "drop"
  )

smry_t_neg <- neg_candidates %>%
  dplyr::inner_join(latest_per_patient, by = c("patient_id_mskcc", "timepoint_days_since_start_of_RT")) %>%
  dplyr::left_join(
    dplyr::select(mrd_smry, sample_name, `MRD-Landmark_Result`),
    by = "sample_name"
  ) %>%
  dplyr::filter(`MRD-Landmark_Result` == "ABSENT") %>%
  dplyr::mutate(Is_ctDNA = "-ve")

shared_cols <- intersect(colnames(smry_t_pos), colnames(smry_t_neg))
smry_ft <- dplyr::bind_rows(
  dplyr::select(smry_t_pos, all_of(shared_cols)),
  dplyr::select(smry_t_neg, all_of(shared_cols))
)

# --- Mutation AF summary joined to insert size metrics ---
# Built once; downstream helpers filter for their subset.
mut_af_smry <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(
    mean_af   = mean(t_maf),
    median_af = median(t_maf),
    max_af    = max(t_maf),
    .groups   = "drop"
  ) %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode)

smry_base <- insert_size_metrics %>%
  dplyr::left_join(mut_af_smry, by = "sample_name") %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::mutate(hpv_type_wes_wgs = dplyr::coalesce(hpv_type_wes_wgs, "Unknown")) %>%
  dplyr::mutate(
    chromosome = vapply(TARGET_REGION, function(x) strsplit(x, ":", fixed = TRUE)[[1]][1], character(1)),
    start      = vapply(TARGET_REGION, function(x) strsplit(x, ":|-", perl = TRUE)[[1]][2], character(1)),
    end        = vapply(TARGET_REGION, function(x) strsplit(x, ":|-", perl = TRUE)[[1]][3], character(1))
  ) %>%
  readr::type_convert() %>%
  dplyr::left_join(bed_file, by = c("chromosome", "start", "end")) %>%
  dplyr::mutate(
    chromosome = dplyr::recode(chromosome, !!!contig_to_hpv),
    mean_af    = dplyr::if_else(mean_af   == 0, 1e-6, mean_af),
    median_af  = dplyr::if_else(median_af == 0, 1e-6, median_af),
    max_af     = dplyr::if_else(max_af    == 0, 1e-6, max_af),
    start_end  = paste0(start, ":", end),
    aligned_reads = log10(READ_PAIRS + 1),
    insert_size   = log10(MEAN_INSERT_SIZE + 1)
  )
```

```{r build_lda_inputs, eval = TRUE, include = FALSE}

# --- Helper: pivot smry_ subset into wide LDA feature matrix ---
# formula_vars: character vector of grouping cols beyond sample_name (e.g. "Is_ctDNA")
pivot_to_matrix <- function(df, formula_vars = character(0)) {
  id_vars    <- c("sample_name", formula_vars)
  read_cols  <- setNames(
    paste0(target_names, "_READ_COUNT"),
    sub("_.*", "", target_names)  # E1, E2, ...
  )
  ins_cols <- setNames(
    paste0(target_names, "_INSERT_SIZE"),
    sub("_.*", "", target_names)
  )

  reads_wide <- reshape2::dcast(
    df,
    formula = as.formula(paste(paste(id_vars, collapse = " + "), "~ gene_name + start_end")),
    value.var = "aligned_reads",
    fill = 0
  ) %>%
    dplyr::rename(
      `E1_1:1950_READ_COUNT`    = `E1_1:1950`,
      `E2_1891:2989_READ_COUNT` = `E2_1891:2989`,
      `E5_2985:3237_READ_COUNT` = `E5_2985:3237`,
      `E6_7124:7601_READ_COUNT` = `E6_7124:7601`,
      `E7_7603:7900_READ_COUNT` = `E7_7603:7900`,
      `L1_4774:6292_READ_COUNT` = `L1_4774:6292`
    )

  ins_wide <- reshape2::dcast(
    df,
    formula = as.formula(paste(paste(id_vars, collapse = " + "), "~ gene_name + start_end")),
    value.var = "insert_size",
    fill = 0
  ) %>%
    dplyr::rename(
      `E1_1:1950_INSERT_SIZE`    = `E1_1:1950`,
      `E2_1891:2989_INSERT_SIZE` = `E2_1891:2989`,
      `E5_2985:3237_INSERT_SIZE` = `E5_2985:3237`,
      `E6_7124:7601_INSERT_SIZE` = `E6_7124:7601`,
      `E7_7603:7900_INSERT_SIZE` = `E7_7603:7900`,
      `L1_4774:6292_INSERT_SIZE` = `L1_4774:6292`
    )

  dplyr::left_join(reads_wide, ins_wide, by = id_vars) %>%
    tibble::column_to_rownames(var = "sample_name")
}

# --- Helper: LDA simulation grid (shared across all three sets) ---
make_sim_grid <- function(n_tiles = N_TILES) {
  ar  <- seq(0, 6, length.out = n_tiles)
  ins <- seq(0, 3, length.out = n_tiles)
  dplyr::tibble(insert_size = rep(ins, each = n_tiles), aligned_reads = rep(ar, n_tiles)) %>%
    dplyr::mutate(
      `E1_1:1950_READ_COUNT`    = aligned_reads,
      `E2_1891:2989_READ_COUNT` = aligned_reads,
      `E5_2985:3237_READ_COUNT` = aligned_reads,
      `E6_7124:7601_READ_COUNT` = aligned_reads,
      `E7_7603:7900_READ_COUNT` = aligned_reads,
      `L1_4774:6292_READ_COUNT` = aligned_reads,
      `E1_1:1950_INSERT_SIZE`    = insert_size,
      `E2_1891:2989_INSERT_SIZE` = insert_size,
      `E5_2985:3237_INSERT_SIZE` = insert_size,
      `E6_7124:7601_INSERT_SIZE` = insert_size,
      `E7_7603:7900_INSERT_SIZE` = insert_size,
      `L1_4774:6292_INSERT_SIZE` = insert_size
    ) %>%
    dplyr::select(-aligned_reads, -insert_size)
}

# --- Helper: run per-gene LDA and collect observed + simulated results ---
run_lda_per_gene <- function(training_mat, test_mat, sim_grid, has_label = TRUE) {
  observed  <- vector("list", length(target_names))
  simulated <- vector("list", length(target_names))
  mat_      <- sim_grid

  for (i in seq_along(target_names)) {
    rc_col  <- paste0(target_names[i], "_READ_COUNT")
    ins_col <- paste0(target_names[i], "_INSERT_SIZE")

    fit_ <- MASS::lda(
      Is_ctDNA ~ .,
      data = training_mat %>% dplyr::select(all_of(c("Is_ctDNA", rc_col, ins_col)))
    )
    res_ <- predict(fit_, newdata = test_mat %>% dplyr::select(all_of(c(rc_col, ins_col))))
    sim_ <- predict(fit_, newdata = mat_    %>% dplyr::select(all_of(c(rc_col, ins_col))))

    obs_df <- test_mat %>%
      dplyr::mutate(
        Pr          = res_$posterior[, "+ve"],
        Is_ctDNA    = res_$class,
        target_name = target_names[i],
        sample_name = rownames(test_mat)
      ) %>%
      dplyr::rename(read_count = !!rc_col, insert_size = !!ins_col) %>%
      dplyr::select(Pr, read_count, insert_size, target_name, sample_name)

    if (has_label) {
      obs_df <- test_mat %>%
        dplyr::mutate(
          Pr          = res_$posterior[, "+ve"],
          Is_ctDNA    = if ("Is_ctDNA" %in% colnames(test_mat)) Is_ctDNA else res_$class,
          target_name = target_names[i],
          sample_name = rownames(test_mat)
        ) %>%
        dplyr::rename(read_count = !!rc_col, insert_size = !!ins_col) %>%
        dplyr::select(any_of(c("Is_ctDNA", "Pr", "read_count", "insert_size", "target_name", "sample_name")))
    }

    observed[[i]]  <- obs_df
    simulated[[i]] <- mat_ %>%
      dplyr::mutate(
        Pr          = sim_$posterior[, "+ve"],
        target_name = target_names[i]
      ) %>%
      dplyr::rename(read_count = !!rc_col, insert_size = !!ins_col) %>%
      dplyr::select(Pr, read_count, insert_size, target_name)
  }
  list(observed = observed, simulated = simulated)
}

mat_ <- make_sim_grid()

# --- Training set: HPV-16, in smry_ft ---
smry_train <- smry_base %>%
  dplyr::left_join(dplyr::select(smry_ft, sample_name, Is_ctDNA), by = "sample_name") %>%
  dplyr::filter(!is.na(Is_ctDNA), chromosome == "HPV-16", hpv_type_wes_wgs == "HPV-16") %>%
  dplyr::mutate(
    Is_ctDNA = dplyr::case_when(
      hpv_type_wes_wgs == "HPV-16" & Is_ctDNA == "+ve" ~ "+ve",
      TRUE ~ "-ve"
    ),
    Is_ctDNA = factor(Is_ctDNA, levels = c("+ve", "-ve"), ordered = TRUE)
  )

data_ <- pivot_to_matrix(smry_train, formula_vars = "Is_ctDNA") %>%
  dplyr::mutate(Is_ctDNA = factor(Is_ctDNA, levels = c("+ve", "-ve"), ordered = TRUE))

lda_train <- run_lda_per_gene(data_, data_, mat_, has_label = TRUE)
TRAINING  <- lda_train$observed

# --- Test set: HPV-16 positive, not in smry_ft ---
smry_test_pos <- smry_base %>%
  dplyr::filter(
    chromosome == "HPV-16",
    hpv_type_wes_wgs == "HPV-16",
    !(sample_name %in% smry_ft$sample_name)
  )

training_ <- pivot_to_matrix(smry_train, formula_vars = "Is_ctDNA") %>%
  dplyr::mutate(Is_ctDNA = factor(Is_ctDNA, levels = c("+ve", "-ve"), ordered = TRUE))

test_pos_ <- pivot_to_matrix(smry_test_pos)

lda_test_pos <- run_lda_per_gene(training_, test_pos_, mat_)
TEST_POS     <- lda_test_pos$observed

# --- Test set: outgroup — HPV-16 alignments from non-HPV-16 patients ---
smry_test_neg <- smry_base %>%
  dplyr::filter(
    chromosome == "HPV-16",
    hpv_type_wes_wgs %in% c("HPV-18", "HPV-33", "HPV-35", "HPV-58"),
    !(sample_name %in% smry_ft$sample_name)
  )

test_neg_ <- pivot_to_matrix(smry_test_neg)

lda_test_neg <- run_lda_per_gene(training_, test_neg_, mat_)
TEST_NEG     <- lda_test_neg$observed
```

```{r build_pca_plots, eval = TRUE, include = FALSE}

# --- Helper: build a PCA-based ggplot from TRAINING / TEST_POS / TEST_NEG lists ---
build_pca_plot <- function(value_col, x_limits, y_limits, plot_title) {
  train_ <- dplyr::tibble(
    Is_ctDNA = TRAINING[[1]]$Is_ctDNA,
    E1 = TRAINING[[1]][[value_col]],
    E2 = TRAINING[[2]][[value_col]],
    E5 = TRAINING[[3]][[value_col]],
    E6 = TRAINING[[4]][[value_col]],
    E7 = TRAINING[[5]][[value_col]],
    L1 = TRAINING[[6]][[value_col]]
  )

  test_pos <- dplyr::tibble(
    E1 = TEST_POS[[1]][[value_col]], E2 = TEST_POS[[2]][[value_col]],
    E5 = TEST_POS[[3]][[value_col]], E6 = TEST_POS[[4]][[value_col]],
    E7 = TEST_POS[[5]][[value_col]], L1 = TEST_POS[[6]][[value_col]]
  )

  test_neg <- dplyr::tibble(
    E1 = TEST_NEG[[1]][[value_col]], E2 = TEST_NEG[[2]][[value_col]],
    E5 = TEST_NEG[[3]][[value_col]], E6 = TEST_NEG[[4]][[value_col]],
    E7 = TEST_NEG[[5]][[value_col]], L1 = TEST_NEG[[6]][[value_col]]
  )

  pca_fit <- train_ %>%
    dplyr::select(where(is.numeric)) %>%
    prcomp()

  pca_fit %>%
    broom::augment(train_) %>%
    dplyr::rename_with(~ gsub("\\.fittedPC", "PC", .x), contains(".fittedPC")) %>%
    dplyr::select(-`.rownames`) %>%
    dplyr::mutate(Data_partition = "Training") %>%
    dplyr::bind_rows(
      predict(pca_fit, newdata = test_pos) %>%
        dplyr::as_tibble() %>%
        dplyr::mutate(Data_partition = "Test", Is_ctDNA = "Unknown")
    ) %>%
    dplyr::bind_rows(
      predict(pca_fit, newdata = test_neg) %>%
        dplyr::as_tibble() %>%
        dplyr::mutate(Data_partition = "Outgroup\n(HPV-16 -ve)", Is_ctDNA = "Pseudo -ve")
    ) %>%
    readr::type_convert() %>%
    dplyr::mutate(
      Data_partition = factor(Data_partition,
        levels = c("Training", "Test", "Outgroup\n(HPV-16 -ve)"), ordered = TRUE),
      Is_ctDNA = factor(Is_ctDNA,
        levels = c("+ve", "-ve", "Pseudo -ve", "Unknown"), ordered = TRUE)
    ) %>%
    ggplot(aes(x = PC1, y = PC2, color = Data_partition, shape = Is_ctDNA)) +
    geom_point(stat = "identity", size = 2.5, alpha = 0.85) +
    scale_color_brewer(type = "qual", palette = 6) +
    scale_shape_manual(values = c(21, 22, 24, 25)) +
    xlab("Principal Component 1") +
    ylab("Principal Component 2") +
    labs(title = plot_title) +
    scale_x_continuous(limits = x_limits) +
    scale_y_continuous(limits = y_limits) +
    theme_classic() +
    theme(
      axis.title.x = element_text(margin = ggplot2::margin(t = 20)),
      axis.title.y = element_text(margin = ggplot2::margin(r = 20)),
      plot.title   = element_text(hjust = 0.5, size = 10)
    ) +
    guides(
      color = guide_legend(title = "Data partition", override.aes = list(shape = 23), order = 1),
      shape = guide_legend(title = "ctDNA",          override.aes = list(color = "black"), order = 2)
    )
}

plot_pca_read_count <- build_pca_plot(
  value_col   = "read_count",
  x_limits    = c(-6, 6),
  y_limits    = c(-1, 1),
  plot_title  = "HPV-16 Aligned Read Pairs"
)

plot_pca_insert_size <- build_pca_plot(
  value_col   = "insert_size",
  x_limits    = c(-1, 1),
  y_limits    = c(-0.5, 0.5),
  plot_title  = "HPV-16 Mean Insert Size"
)
```
<br/>
<br/>
```{r plot_pca_read_counts, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 4, fig.width = 5.75, fig.cap = '<br/>**Supplementary Figure S3a** PCA of aligned read pairs across all samples.'}

print(plot_pca_read_count)
```
<br/>
<br/>
```{r plot_pca_insert_size, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 4, fig.width = 5.75, fig.cap = '<br/>**Supplementary Figure S3b** PCA of mean insert sizes across all samples.'}

print(plot_pca_insert_size)
```
