---
title: "Supplementary Figure S9 - Dynamic response assessment using dual-assay ctDNA and imaging in HPV-associated OPC"
author:
  - name: David N Brown, Bill H Diplas
    affiliation: Memorial Sloan Kettering Cancer Center
output:
  html_document:
    theme: cerulean
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r load_shared_data, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}

suppressPackageStartupMessages(library("gdata"))
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("readr"))
suppressPackageStartupMessages(library("data.table"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("reshape2"))
suppressPackageStartupMessages(library("magrittr"))
suppressPackageStartupMessages(library("tidyr"))
suppressPackageStartupMessages(library("fuzzyjoin"))
suppressPackageStartupMessages(library("pander"))
suppressPackageStartupMessages(library("ggsignif"))
suppressPackageStartupMessages(library("ggrepel"))
suppressPackageStartupMessages(library("ggforce"))
suppressPackageStartupMessages(library("ggord"))
suppressPackageStartupMessages(library("ggpubr"))
suppressPackageStartupMessages(library("ggridges"))
suppressPackageStartupMessages(library("gghalves"))
suppressPackageStartupMessages(library("cowplot"))
suppressPackageStartupMessages(library("viridis"))
suppressPackageStartupMessages(library("superheat"))
suppressPackageStartupMessages(library("ComplexHeatmap"))
suppressPackageStartupMessages(library("grid"))
suppressPackageStartupMessages(library("gridExtra"))
suppressPackageStartupMessages(library("drc"))
suppressPackageStartupMessages(library("preseqR"))
suppressPackageStartupMessages(library("foreach"))
suppressPackageStartupMessages(library("parallel"))
suppressPackageStartupMessages(library("doMC"))
suppressPackageStartupMessages(library("maftools"))
suppressPackageStartupMessages(library("RColorBrewer"))
suppressPackageStartupMessages(library("pROC"))
suppressPackageStartupMessages(library("MASS"))
suppressPackageStartupMessages(library("rpart"))
suppressPackageStartupMessages(library("klaR"))
suppressPackageStartupMessages(library("PMCMRplus"))
suppressPackageStartupMessages(library("ellipse"))
suppressPackageStartupMessages(library("ggbeeswarm"))
suppressPackageStartupMessages(library("corrplot"))
suppressPackageStartupMessages(library("org.Hs.eg.db"))
suppressPackageStartupMessages(library("GSVA"))
suppressPackageStartupMessages(library("GSVAdata"))
suppressPackageStartupMessages(library("GSEABase"))
suppressPackageStartupMessages(library("fgsea"))
suppressPackageStartupMessages(library("genefilter"))
suppressPackageStartupMessages(library("limma"))
suppressPackageStartupMessages(library("sensemakr"))
suppressPackageStartupMessages(library("Rtsne"))
suppressPackageStartupMessages(library("ggdendro"))
suppressPackageStartupMessages(library("rpart.plot"))
suppressPackageStartupMessages(library("plyr"))
suppressPackageStartupMessages(library("ipred"))
suppressPackageStartupMessages(library("vip"))
suppressPackageStartupMessages(library("e1071"))
suppressPackageStartupMessages(library("TCGAmutations"))
suppressPackageStartupMessages(library("party"))
suppressPackageStartupMessages(library("partykit"))
suppressPackageStartupMessages(library("ggparty"))
suppressPackageStartupMessages(library("randomForest"))
suppressPackageStartupMessages(library("survival"))
suppressPackageStartupMessages(library("survminer"))

registerDoMC(8)

FRAGMENT_LENGTH_THRESHOLD = 37
N_TILES = 250
USE_ALL = TRUE

url_manifest <- "../data/manifest.txt"
url_primers <- "../data/HPV_primers.bed"
url_bed_file <- "../data/hpv_31_33_35H_16_18.bed"
url_gene_coords <- "../data/gene_coords.txt"
url_preanalytical_conidtions <- "../data/pre-analytical_conditions.txt"
url_mrd_summary <- "../data/TM-2021-MSK-002_MRD_Results_Summary_20220825.txt"
url_mutation_summary <- "../data/mutation_summary.maf"
url_hpv_type <- "../data/TM-2021-MSK-002_HPV_Typing_WES_WGS.txt"
url_no_node_dissection <- "../data/patients_0_nodal_dissection.txt"
url_clinical <- "../data/clinical.txt"
url_tumor_variants <- "../data/all_variants.txt"
url_hotspots <- "../data/hotspots.txt"
url_aln_metrics <- "../data/aln_metrics.txt"
url_aln_metrics_ft <- "../data/aln_metrics_ft.txt"
url_hs_metrics <- "../data/hs_metrics.txt"
url_hs_metrics_ft <- "../data/hs_metrics_ft.txt"
url_hs_target_metrics <- "../data/hs_metrics_target.txt"
url_hs_target_metrics_ft <- "../data/hs_metrics_target_ft.txt"
url_idx_metrics <- "../data/idx_metrics.txt"
url_idx_metrics_ft <- "../data/idx_metrics_ft.txt"
url_insert_metrics <- "../data/insert_metrics.txt"
url_insert_metrics_ft <- "../data/insert_metrics_ft.txt"
url_insert_metrics_by_gene <- "../data/insert_metrics_by_gene.txt"
url_insert_summary <- "../data/insert_summary.txt"
url_insert_summary_ft <- "../data/insert_summary_ft.txt"
url_gatk_summary <- "../data/gatk_summary.txt"
url_tpm_by_gene <- "../data/tpm_by_gene.txt"

url_tcga_clinical <- "../data/clinical_tcga_hnsc_mc3.txt"

url_gene_list <- list(
	"foundation_one" = "../data/Foundation_One_Liquid_CDx.txt",
	"guardant_360" = "../data/Guardant_360_CDx.txt",
	"msk_accessv1" = "../data/MSK-ACCESS-v2_0.txt"
)

target_contigs <- c("HPV-16" = "NC001526.4",
		    "HPV-18" = "NC001357.1",
		    "HPV-31" = "J04353.1",
		    "HPV-33" = "M12732.1",
		    "HPV-35" = "X74477.1")

'scientific_10' <- function(x) {
	parse(text=gsub("+", "", gsub("e", " %.% 10^", scales::scientific_format()(x)), , fixed = TRUE))
}

'scientific_1e' <- function(x) {
	parse(text=gsub("+", "", gsub("1e", " 10^", scales::scientific_format()(x)), , fixed = TRUE))
}

'log_10' <- function(x) {
	parse(text=gsub("+", "", gsub("e", " %.% 10^-", scales::scientific_format()(x)), fixed=TRUE))
}


'str_split' <- function(x, split, n) {
	return(invisible(unlist(strsplit(x, split = split))[n]))
}

'fGSEA' <- function(fold_change, gmt_file, pval = 1) {
	set.seed(54321)
	msig_db = fgsea::gmtPathways(gmt_file)
	gsea = fgsea::fgsea(pathways = msig_db,
			    stats = fold_change,
			    minSize = 5,
			    maxSize = 500,
			    nperm = 10000) %>% 
		dplyr::as_tibble() %>% 
		dplyr::filter(padj < !!pval) %>% 
		dplyr::arrange(desc(NES))
	
	return(invisible(gsea))
}

'margin' <- ggplot2::margin

manifest = readr::read_tsv(file = url_manifest, col_names = TRUE, col_types = cols(.default = col_character())) %>%
	   readr::type_convert() %>%
	   dplyr::filter(!is.na(bam_file_name_hpv)) %>%
	   dplyr::mutate(sample_uuid = paste0(sample_id_mskcc, "-", sample_id_invitae))

mrd_smry = readr::read_tsv(file = url_mrd_summary, col_names = TRUE, col_types = cols(.default = col_character())) %>%
	   readr::type_convert()

preanalytical_conditions = readr::read_tsv(file = url_preanalytical_conidtions, col_names = TRUE, col_types = cols(.default = col_character())) %>%
			   readr::type_convert()

hpv_smry = readr::read_tsv(file = url_hpv_type, col_names = TRUE, col_types = cols(.default = col_character())) %>%
	   readr::type_convert() %>%
	   dplyr::mutate(patient_id_mskcc = gsub(pattern = "-T", replacement = "", x= patient_name, fixed = TRUE)) %>%
	   dplyr::mutate(hpv_type_wes = gsub("HPV", "HPV-", hpv_type_wes, fixed = TRUE)) %>%
	   dplyr::mutate(hpv_type_wgs = gsub("HPV", "HPV-", hpv_type_wgs, fixed = TRUE)) %>%
	   dplyr::mutate(hpv_type_wes_wgs = gsub("HPV", "HPV-", hpv_type_wes_wgs, fixed = TRUE)) %>%
	   dplyr::mutate(hpv_type_wes_wgs = case_when(
		   is.na(hpv_type_wes_wgs) ~ "Unknown",
		   TRUE ~ hpv_type_wes_wgs
	   ))

nodal_dissection_smry = readr::read_tsv(file = url_no_node_dissection, col_names = TRUE, col_types = cols(.default = col_character())) %>%
			readr::type_convert() %>%
			dplyr::rename(patient_id_mskcc = sample)

manifest = manifest %>%
	   dplyr::left_join(preanalytical_conditions, by = "sample_id_mskcc") %>%
	   dplyr::mutate(patient_id_mskcc = case_when(
		   is.na(patient_id_mskcc) & sample_id_mskcc=="21-144-03654" ~ "CTMS-164",
		   TRUE ~ patient_id_mskcc
	   )) %>%
	   dplyr::mutate(sample_name = paste0(sample_id_mskcc, "-", sample_id_invitae)) %>%
	   dplyr::left_join(hpv_smry, by = "patient_id_mskcc")

insert_size_metrics = readr::read_tsv(file = url_insert_metrics, col_names = TRUE, col_types = cols(.default = col_character())) %>%
		      readr::type_convert()

insert_size_metrics_ft = readr::read_tsv(file = url_insert_metrics_ft, col_names = TRUE, col_types = cols(.default = col_character())) %>%
		      	 readr::type_convert()

insert_size_smry = readr::read_tsv(file = url_insert_summary, col_names = TRUE, col_types = cols(.default = col_character())) %>%
		   readr::type_convert()

insert_size_smry_ft = readr::read_tsv(file = url_insert_summary_ft, col_names = TRUE, col_types = cols(.default = col_character())) %>%
		      readr::type_convert()

insert_size_smry = insert_size_smry %>%
		   dplyr::group_by(SAMPLE_NAME) %>%
		   dplyr::summarize(TOTAL_READS = sum(READ_COUNT)) %>%
		   dplyr::ungroup() %>%
		   dplyr::right_join(insert_size_smry, by = "SAMPLE_NAME") %>%
		   dplyr::mutate(`%_READS` = READ_COUNT/TOTAL_READS)

insert_size_smry_ft = insert_size_smry_ft %>%
		      dplyr::group_by(SAMPLE_NAME, FRAGMENT_LENGTH) %>%
		      dplyr::summarize(TOTAL_READS = sum(READ_COUNT)) %>%
		      dplyr::ungroup() %>%
		      dplyr::right_join(insert_size_smry_ft, by = c("SAMPLE_NAME", "FRAGMENT_LENGTH")) %>%
		      dplyr::mutate(`%_READS` = READ_COUNT/TOTAL_READS)

primer_set = readr::read_tsv(file = url_primers, col_names = FALSE, col_types = cols(.default = col_character())) %>%
	     readr::type_convert() %>%
	     dplyr::mutate(insert_size = X3 - X2)

mutation_smry = readr::read_tsv(file = url_mutation_summary, col_names = TRUE, col_types = cols(.default = col_character())) %>%
		readr::type_convert()

clinical = readr::read_tsv(file = url_clinical, col_names = TRUE, col_types = cols(.default = col_character())) %>%
	   readr::type_convert()

posterior_probability = readr::read_tsv(file = "../res/Posterior_Probability_ALL.txt", col_names = TRUE, col_types = cols(.default = col_character())) %>%
			readr::type_convert() %>%
			dplyr::mutate(timepoint_weeks_since_start_of_RT = floor(timepoint_days_since_start_of_RT/7)) %>%
			dplyr::mutate(timepoint_weeks_since_start_of_RT = case_when(
				timepoint_weeks_since_start_of_RT < 0 ~ "Pre-treatment",
				TRUE ~ paste0("wk", timepoint_weeks_since_start_of_RT)
			))

idx_metrics_ft = readr::read_tsv(file = url_idx_metrics_ft, col_names = TRUE, col_types = cols(.default = col_character())) %>%
	      	 readr::type_convert() %>%
		 dplyr::select(sample_name = SAMPLE_NAME, contig = CHROMOSOME, aligned_reads = ALIGNED_READS, fragment_length = FRAGMENT_LENGTH) %>%
		 dplyr::left_join(dplyr::tibble(contig = target_contigs,
				       		chromosome = names(target_contigs)),
				  by = "contig") %>%
		 dplyr::filter(fragment_length == FRAGMENT_LENGTH_THRESHOLD) %>%
		 dplyr::filter(!is.na(chromosome)) %>%
		 dplyr::left_join(manifest, by = "sample_name") %>%
		 dplyr::filter(chromosome == hpv_type_wes_wgs) %>%
		 dplyr::left_join(mutation_smry %>%
				       dplyr::filter(FILTER == "PASS") %>%
				       dplyr::group_by(Tumor_Sample_Barcode) %>%
				       dplyr::summarize(mean_af = mean(t_maf)) %>%
				       dplyr::ungroup() %>%
				       dplyr::rename(sample_name = Tumor_Sample_Barcode),
				       by = "sample_name") %>%
		dplyr::mutate(timepoint_weeks_since_start_of_RT = floor(timepoint_days_since_start_of_RT/7)) %>%
		dplyr::mutate(timepoint_weeks_since_start_of_RT = case_when(
			timepoint_weeks_since_start_of_RT < 0 ~ "Pre-treatment",
			TRUE ~ paste0("wk", timepoint_weeks_since_start_of_RT)
		))
		
plot_mri = clinical %>%
	dplyr::select(patient_id_mskcc,
		      `Pre-treatment` = MRI_rawdata_wk0,
		      `wk1` = MRI_rawdata_wk1,
		      `wk2` = MRI_rawdata_wk2,
		      `wk3` = MRI_rawdata_wk3) %>%
	reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "MRI_volume") %>%
	dplyr::left_join(manifest %>%
			 dplyr::group_by(patient_id_mskcc) %>%
			 dplyr::summarize(hpv_type_wes_wgs = unique(hpv_type_wes_wgs)),
			 by = "patient_id_mskcc") %>%
	tidyr::drop_na() %>%
	dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
	dplyr::filter(timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")) %>%
	dplyr::mutate(timepoint_weeks_since_start_of_RT = factor(x = timepoint_weeks_since_start_of_RT,
								 levels = c("Pre-treatment", "wk1", "wk2", "wk3"),
								 ordered = TRUE)) %>%
	ggplot(aes(x = timepoint_weeks_since_start_of_RT, y = MRI_volume*0.001,
		   fill = timepoint_weeks_since_start_of_RT)) +
	geom_line(aes(group = patient_id_mskcc), size = .1, alpha = 1, color = "black") +
	geom_point(stat = "identity", shape = 21, size = 2, alpha = 1, color = "black") +
	scale_fill_brewer(type = "seq", palette = "YlGnBu", direction = -1) +
	scale_x_discrete(breaks = c("Pre-treatment", "wk1", "wk2", "wk3"),
			 labels = c("Pre-treatment", "Week 1", "Week 2", "Week 3")) +
	scale_y_log10(labels = scientific_10) +
	xlab("") +
	ylab(expression("MRI Volume ("~cm^3~")")) +
	theme_classic() +
	theme(axis.title.x = element_text(margin = margin(t = 20)),
	      axis.title.y = element_text(margin = margin(r = 20)),
	      axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1),
	      axis.text.y = element_text(size = 10)) +
	guides(fill = FALSE, color = FALSE)
	
plot_adc = clinical %>%
	dplyr::select(patient_id_mskcc,
		      `Pre-treatment` = ADC_Mean_wk0,
		      `wk1` = ADC_Mean_wk1,
		      `wk2` = ADC_Mean_wk2,
		      `wk3` = ADC_Mean_wk3) %>%
	reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "ADC") %>%
	dplyr::left_join(manifest %>%
			 dplyr::group_by(patient_id_mskcc) %>%
			 dplyr::summarize(hpv_type_wes_wgs = unique(hpv_type_wes_wgs)),
			 by = "patient_id_mskcc") %>%
	tidyr::drop_na() %>%
	dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
	dplyr::filter(timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")) %>%
	dplyr::mutate(timepoint_weeks_since_start_of_RT = factor(x = timepoint_weeks_since_start_of_RT,
								 levels = c("Pre-treatment", "wk1", "wk2", "wk3"),
								 ordered = TRUE)) %>%
	ggplot(aes(x = timepoint_weeks_since_start_of_RT, y = ADC,
		   fill = timepoint_weeks_since_start_of_RT)) +
	geom_line(aes(group = patient_id_mskcc), size = .1, alpha = 1, color = "black") +
	geom_point(stat = "identity", shape = 21, size = 2, alpha = 1, color = "black") +
	scale_fill_brewer(type = "seq", palette = "YlGnBu", direction = -1) +
	scale_x_discrete(breaks = c("Pre-treatment", "wk1", "wk2", "wk3"),
			 labels = c("Pre-treatment", "Week 1", "Week 2", "Week 3")) +
	scale_y_log10(limits = c(.4, 2.1),
		      breaks = c(.5, 1, 2),
		      labels = c(.5, 1, 2)) +
	xlab("") +
	ylab(expression("ADC ("%.%10^-3~mm^2~sec^-1~")")) +
	theme_classic() +
	theme(axis.title.x = element_text(margin = margin(t = 20)),
	      axis.title.y = element_text(margin = margin(r = 30)),
	      axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1),
	      axis.text.y = element_text(size = 10)) +
	guides(fill = FALSE, color = FALSE)
	
plot_maf = idx_metrics_ft %>%
	dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
	dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
	dplyr::summarize(mean_af = mean(mean_af)) %>%
	dplyr::filter(timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")) %>%
	dplyr::mutate(timepoint_weeks_since_start_of_RT = factor(x = timepoint_weeks_since_start_of_RT,
								 levels = c("Pre-treatment", "wk1", "wk2", "wk3"),
								 ordered = TRUE)) %>%
	ggplot(aes(x = timepoint_weeks_since_start_of_RT, y = (mean_af*100)+(1E-3),
		   fill = timepoint_weeks_since_start_of_RT)) +
	geom_line(aes(group = patient_id_mskcc), size = .1, alpha = 1, color = "black") +
	geom_point(stat = "identity", shape = 21, size = 2, alpha = 1, color = "black") +
	scale_fill_brewer(type = "seq", palette = "YlGnBu", direction = -1) +
	scale_x_discrete(breaks = c("Pre-treatment", "wk1", "wk2", "wk3"),
			 labels = c("Pre-treatment", "Week 1", "Week 2", "Week 3")) +
	scale_y_log10(limits = c(NA, 110),
		      breaks = c(.001, .01, .1, 1, 10, 100),
		      labels = c(".001", ".01", ".1", "1", "10", "100")) +
	xlab("") +
	ylab("ctDNA Fraction (%)") +
	theme_classic() +
	theme(axis.title.x = element_text(margin = margin(t = 20)),
	      axis.title.y = element_text(margin = margin(r = 30)),
	      axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1),
	      axis.text.y = element_text(size = 10)) +
	guides(fill = FALSE, color = FALSE)
	
plot_readcounts = idx_metrics_ft %>%
	dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
	dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
	dplyr::summarize(aligned_reads = mean(log10(aligned_reads))) %>%
	dplyr::filter(timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")) %>%
	dplyr::mutate(timepoint_weeks_since_start_of_RT = factor(x = timepoint_weeks_since_start_of_RT,
								 levels = c("Pre-treatment", "wk1", "wk2", "wk3"),
								 ordered = TRUE)) %>%
	ggplot(aes(x = timepoint_weeks_since_start_of_RT, y = aligned_reads,
		   fill = timepoint_weeks_since_start_of_RT)) +
	geom_line(aes(group = patient_id_mskcc), size = .1, alpha = 1, color = "black") +
	geom_point(stat = "identity", shape = 21, size = 2, alpha = 1, color = "black") +
	scale_fill_brewer(type = "seq", palette = "YlGnBu", direction = -1) +
	scale_x_discrete(breaks = c("Pre-treatment", "wk1", "wk2", "wk3"),
			 labels = c("Pre-treatment", "Week 1", "Week 2", "Week 3")) +
	scale_y_continuous(limits = c(.5, 7),
			   breaks = c(2, 3, 4, 5, 6, 7),
			   labels = scientific_10(10^c(2, 3, 4, 5, 6, 7))) +
	xlab("") +
	ylab("cfDNA Aligned HPV Read Pairs") +
	theme_classic() +
	theme(axis.title.x = element_text(margin = margin(t = 20)),
	      axis.title.y = element_text(margin = margin(r = 20)),
	      axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1),
	      axis.text.y = element_text(size = 10)) +
	guides(fill = FALSE, color = FALSE)
	
```

```{r plot_mri, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 3.65, fig.cap = '<br/>**Supplementary Figure S9a** Distribution of imaging (T2 MRI volume) across weekly measurements.'}

print(plot_mri)
```

```{r plot_adc, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 3.65, fig.cap = '<br/>**Supplementary Figure S9a** Distribution of imaging (DW MRI mean ADC) across weekly measurements.'}

print(plot_adc)
```

```{r plot_ctdna_frac, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 3.65, fig.cap = '<br/>**Supplementary Figure S9a** Distribution of ctDNA fraction inferred from PCM across weekly measurements.'}

print(plot_maf)
```

```{r plot_readcounts, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 3.65, fig.cap = '<br/>**Supplementary Figure S9a** Distribution of circulating HPV-16 read pairs across weekly measurements.'}

print(plot_readcounts)
```


```{r patient_ctms30, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}

#==================================================
# Mean AF by Week (CTMS-30)
#==================================================
p_mrd = idx_metrics_ft %>%
	dplyr::left_join(mrd_smry %>%
			 dplyr::mutate(sample_name = gsub(pattern = "EP-D1-D1", replacement = "", x = Sample_ID_Archer, fixed = TRUE)),
			 by = "sample_name") %>%
	dplyr::mutate(Is_ctDNA = case_when(
		`MRD-Monitoring_Result` == "PRESENT" ~ "+ve",
		`MRD-Monitoring_Result` == "ABSENT" ~ "-ve"
	)) %>%
	dplyr::filter(patient_id_mskcc == "CTMS-30") %>%
	dplyr::filter(timepoint_weeks_since_start_of_RT %in% c("wk0", "wk1", "wk2", "wk3")) %>%
	dplyr::mutate(timepoint_weeks_since_start_of_RT = case_when(
		timepoint_weeks_since_start_of_RT == "wk0" ~ "0",
		timepoint_weeks_since_start_of_RT == "wk1" ~ "1",
		timepoint_weeks_since_start_of_RT == "wk2" ~ "2",
		timepoint_weeks_since_start_of_RT == "wk3" ~ "3"
	)) %>%
	readr::type_convert() %>%
	dplyr::select(patient_id_mskcc, timepoint_weeks_since_start_of_RT, measure = mean_af, Is_ctDNA)
p_mrd = p_mrd %>%
	dplyr::mutate(measure = measure / (p_mrd %>%
					   dplyr::filter(timepoint_weeks_since_start_of_RT==0) %>%
					   .[["measure"]])) %>%
	dplyr::mutate(assay = "PCM")

#==================================================
# Number of Read Pairs by Week (CTMS-30)
#==================================================
p_hpv = idx_metrics_ft %>%
	dplyr::left_join(posterior_probability %>%
			 dplyr::select(sample_name, Is_ctDNA), by = "sample_name") %>%
	dplyr::filter(patient_id_mskcc == "CTMS-30") %>%
	dplyr::filter(timepoint_weeks_since_start_of_RT %in% c("wk0", "wk1", "wk2", "wk3")) %>%
	dplyr::mutate(timepoint_weeks_since_start_of_RT = case_when(
		timepoint_weeks_since_start_of_RT == "wk0" ~ "0",
		timepoint_weeks_since_start_of_RT == "wk1" ~ "1",
		timepoint_weeks_since_start_of_RT == "wk2" ~ "2",
		timepoint_weeks_since_start_of_RT == "wk3" ~ "3"
	)) %>%
	readr::type_convert() %>%
	dplyr::select(patient_id_mskcc, timepoint_weeks_since_start_of_RT, measure = aligned_reads, Is_ctDNA)
p_hpv = p_hpv %>%
	dplyr::mutate(measure = measure / (p_hpv %>%
					   dplyr::filter(timepoint_weeks_since_start_of_RT==0) %>%
					   .[["measure"]])) %>%
	dplyr::mutate(assay = "HPV")

#==================================================
# MRI Volume by Week (CTMS-30)
#==================================================
p_mri = clinical %>%
	dplyr::select(patient_id_mskcc,
		      `Pre-treatment` = MRI_rawdata_wk0,
		      `wk1` = MRI_rawdata_wk1,
		      `wk2` = MRI_rawdata_wk2,
		      `wk3` = MRI_rawdata_wk3) %>%
	reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "MRI_volume") %>%
	dplyr::filter(patient_id_mskcc == "CTMS-30") %>%
	dplyr::filter(timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")) %>%
	dplyr::mutate(timepoint_weeks_since_start_of_RT = case_when(
		timepoint_weeks_since_start_of_RT == "Pre-treatment" ~ "0",
		timepoint_weeks_since_start_of_RT == "wk1" ~ "1",
		timepoint_weeks_since_start_of_RT == "wk2" ~ "2",
		timepoint_weeks_since_start_of_RT == "wk3" ~ "3"
	)) %>%
	readr::type_convert() %>%
	dplyr::select(patient_id_mskcc, timepoint_weeks_since_start_of_RT, measure = MRI_volume)
p_mri = p_mri %>%
	dplyr::mutate(measure = measure / (p_mri %>%
					   dplyr::filter(timepoint_weeks_since_start_of_RT==0) %>%
					   .[["measure"]]) - 1) %>%
	dplyr::mutate(measure = ifelse(measure<0, 0, 2*measure)) %>%
	dplyr::mutate(Is_ctDNA = "Not Applicable", assay = "MRI")

#==================================================
# ADC Volume by Week (CTMS-30)
#==================================================
p_adc = clinical %>%
	dplyr::select(patient_id_mskcc,
		      `Pre-treatment` = ADC_Mean_wk0,
		      `wk1` = ADC_Mean_wk1,
		      `wk2` = ADC_Mean_wk2,
		      `wk3` = ADC_Mean_wk3) %>%
	reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "ADC") %>%
	dplyr::filter(patient_id_mskcc == "CTMS-30") %>%
	dplyr::filter(timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")) %>%
	dplyr::mutate(timepoint_weeks_since_start_of_RT = case_when(
		timepoint_weeks_since_start_of_RT == "Pre-treatment" ~ "0",
		timepoint_weeks_since_start_of_RT == "wk1" ~ "1",
		timepoint_weeks_since_start_of_RT == "wk2" ~ "2",
		timepoint_weeks_since_start_of_RT == "wk3" ~ "3"
	)) %>%
	readr::type_convert() %>%
	dplyr::select(patient_id_mskcc, timepoint_weeks_since_start_of_RT, measure = ADC)
p_adc = p_adc %>%
	dplyr::mutate(measure = measure / (p_adc %>%
					   dplyr::filter(timepoint_weeks_since_start_of_RT==0) %>%
					   .[["measure"]]) - 1) %>%
	dplyr::mutate(measure = ifelse(measure<0, 0, 2*measure)) %>%
	dplyr::mutate(Is_ctDNA = "Not Applicable", assay = "ADC")

plot_ctms30 = p_mrd %>%
	dplyr::bind_rows(p_hpv) %>%
	dplyr::bind_rows(p_mri) %>%
	dplyr::bind_rows(p_adc) %>%
	dplyr::mutate(measure = measure * 100) %>%
	dplyr::mutate(assay = factor(assay, levels = c("PCM", "HPV", "MRI", "ADC"), ordered = TRUE)) %>%
	ggplot(aes(x = timepoint_weeks_since_start_of_RT, y = measure, shape = Is_ctDNA, color = assay)) +
	geom_line(mapping = aes(x = timepoint_weeks_since_start_of_RT, y = measure, color = assay),
		  stat = "identity", size = 1.25, alpha = .75, inherit.aes = FALSE) +
	geom_point(stat = "identity", size = 4, fill = "white") +
	scale_shape_manual(values = c(21, 25, 22)) +
	scale_color_brewer(type = "qual", palette = 7) +
	scale_x_continuous(breaks = 0:3,
			   labels = c("Pre-treat\n-ment", "Week 1", "Week 2", "Week 3")) +
	scale_y_continuous(limits = c(-2, 105),
			   breaks = c(0, 25, 50, 75, 100),
			   labels = c(100, 75, 50, 25, 0),
			   sec.axis = sec_axis(trans = ~., name = "Relative Volume and ADC\nIncrease from Baseline (%)\n",
			  		       breaks = c(0, 20, 40, 60, 80, 100), labels = c(0, 20, 40, 60, 80, 100)/2)) +
	xlab("") +
	ylab("Relative Decrease\nfrom Baseline (%)\n") +
	theme_classic() +
	theme(axis.title.x = element_text(margin = margin(t = 20)),
	      axis.text.x = element_text(margin = margin(t = 7), size = 12),
	      axis.text.y = element_text(size = 12)) +
	guides(color = guide_legend(title = "Assay Modality", order = 1),
	       shape = guide_legend(title = "ctDNA Status", order = 2))
```

```{r plot_ctms30, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 6.5, fig.cap = '<br/>**Supplementary Figure S9c** ctDNA dynamic tracking showing the percentage change of imaging and genomic measures from baseline across weeks 1 to 3.'}

print(plot_ctms30)
```
