---
title: "Supplementary Figure S2 - Key characteristics of the machine learning model for detecting tumor-derived circulating HPV (cHPV) in plasma"
author:
  - name: David N Brown, Bill H Diplas
    affiliation: Memorial Sloan Kettering Cancer Center
output:
  html_document:
    theme: cerulean
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
suppressPackageStartupMessages({
  library("ggplot2")
  library("readr")
  library("dplyr")
  library("tidyr")
  library("magrittr")
  library("ggsignif")
})

# --- Data paths ---
url_manifest               <- "../data/manifest.txt"
url_mrd_summary            <- "../data/TM-2021-MSK-002_MRD_Results_Summary_20220825.txt"
url_preanalytical_conditions <- "../data/pre-analytical_conditions.txt"
url_hpv_type               <- "../data/TM-2021-MSK-002_HPV_Typing_WES_WGS.txt"
url_no_node_dissection     <- "../data/patients_0_nodal_dissection.txt"
url_clinical               <- "../data/clinical.txt"
url_mutation_summary       <- "../data/mutation_summary.maf"
url_tumor_variants         <- "../data/all_variants.txt"
url_insert_metrics_by_gene <- "../data/insert_metrics_by_gene.txt"
url_insert_metrics         <- "../data/insert_metrics.txt"
url_insert_metrics_ft      <- "../data/insert_metrics_ft.txt"
url_insert_summary         <- "../data/insert_summary.txt"
url_insert_summary_ft      <- "../data/insert_summary_ft.txt"
url_idx_metrics_ft         <- "../data/idx_metrics_ft.txt"
url_primers                <- "../data/HPV_primers.bed"

target_contigs <- c(
  "HPV-16" = "NC001526.4",
  "HPV-18" = "NC001357.1",
  "HPV-31" = "J04353.1",
  "HPV-33" = "M12732.1",
  "HPV-35" = "X74477.1"
)
```

```{r load_shared_data, eval = TRUE, include = FALSE}

# --- Load each source file once ---
manifest_raw <- readr::read_tsv(
  url_manifest, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::filter(!is.na(bam_file_name_hpv)) %>%
  dplyr::mutate(sample_uuid = paste0(sample_id_mskcc, "-", sample_id_invitae))

preanalytical_conditions <- readr::read_tsv(
  url_preanalytical_conditions, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

mrd_smry <- readr::read_tsv(
  url_mrd_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(sample_uuid = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE))

hpv_smry <- readr::read_tsv(
  url_hpv_type, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    patient_id_mskcc  = gsub("-T", "", patient_name, fixed = TRUE),
    patient_id_mskcc  = gsub("155salv", "155", patient_id_mskcc, fixed = TRUE),
    hpv_type_wes      = gsub("HPV", "HPV-", hpv_type_wes, fixed = TRUE),
    hpv_type_wgs      = gsub("HPV", "HPV-", hpv_type_wgs, fixed = TRUE),
    hpv_type_wes_wgs  = gsub("HPV", "HPV-", hpv_type_wes_wgs, fixed = TRUE),
    hpv_type_wes_wgs  = dplyr::coalesce(hpv_type_wes_wgs, "Unknown")
  )

nodal_dissection_smry <- readr::read_tsv(
  url_no_node_dissection, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(patient_id_mskcc = sample)

mutation_smry <- readr::read_tsv(
  url_mutation_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

clinical <- readr::read_tsv(
  url_clinical, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(Tumor_Sample_Barcode = tumor_id_wes) %>%
  tidyr::drop_na(Tumor_Sample_Barcode) %>%
  dplyr::select(-additional_crt_post_neck_dissection) %>%
  dplyr::mutate(is_selected = 1)

tumor_vars <- readr::read_tsv(
  url_tumor_variants, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

# --- Build enriched manifest (used by all downstream chunks) ---
manifest <- manifest_raw %>%
  dplyr::left_join(preanalytical_conditions, by = "sample_id_mskcc") %>%
  dplyr::mutate(
    patient_id_mskcc = dplyr::case_when(
      is.na(patient_id_mskcc) & sample_id_mskcc == "21-144-03654" ~ "CTMS-164",
      TRUE ~ patient_id_mskcc
    ),
    sample_name = paste0(sample_id_mskcc, "-", sample_id_invitae)
  ) %>%
  dplyr::left_join(hpv_smry, by = "patient_id_mskcc")

# --- Helper: strip "EP-D1-D1" prefix from MRD sample names ---
mrd_smry_named <- mrd_smry %>%
  dplyr::mutate(
    sample_name = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE)
  )

# --- ctDNA-positive training set ---
# Criteria: mean AF > 5%, known HPV type, MRD PRESENT
smry_t_pos <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(mean_af = mean(t_maf), max_af = max(t_maf), .groups = "drop") %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode) %>%
  dplyr::filter(mean_af > 0.05) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::filter(hpv_type_wes_wgs %in% names(target_contigs)) %>%
  dplyr::left_join(
    mrd_smry_named %>%
      dplyr::select(sample_name, `MRD-Landmark_Result`, `MRD-Monitoring_MRD_Quantification`),
    by = "sample_name"
  ) %>%
  dplyr::filter(`MRD-Landmark_Result` == "PRESENT") %>%
  dplyr::mutate(Is_ctDNA = "+ve")

# --- ctDNA-negative training set ---
# Criteria: mean AF < 0.01%, max AF < 0.1%, no nodal dissection >= 2 years,
#           one sample per patient (latest timepoint), MRD ABSENT
neg_candidates <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(mean_af = mean(t_maf), max_af = max(t_maf), .groups = "drop") %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode) %>%
  dplyr::filter(mean_af < 0.0001, max_af < 0.001) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::left_join(nodal_dissection_smry, by = "patient_id_mskcc") %>%
  dplyr::filter(nd_event == 0, timepoint_days_since_start_of_RT > 730)

# Keep only the latest timepoint per patient
latest_per_patient <- neg_candidates %>%
  dplyr::group_by(patient_id_mskcc) %>%
  dplyr::summarize(
    timepoint_days_since_start_of_RT = max(timepoint_days_since_start_of_RT),
    .groups = "drop"
  )

smry_t_neg <- neg_candidates %>%
  dplyr::inner_join(latest_per_patient, by = c("patient_id_mskcc", "timepoint_days_since_start_of_RT")) %>%
  dplyr::left_join(
    mrd_smry_named %>%
      dplyr::select(sample_name, `MRD-Landmark_Result`, `MRD-Monitoring_MRD_Quantification`),
    by = "sample_name"
  ) %>%
  dplyr::filter(`MRD-Landmark_Result` == "ABSENT") %>%
  dplyr::mutate(Is_ctDNA = "-ve")

# --- Combined training set ---
shared_cols <- intersect(colnames(smry_t_pos), colnames(smry_t_neg))
smry_ft <- dplyr::bind_rows(
  dplyr::select(smry_t_pos, all_of(shared_cols)),
  dplyr::select(smry_t_neg, all_of(shared_cols))
)

# --- Metrics data ---
insert_size_metrics <- readr::read_tsv(
  url_insert_metrics, col_names = TRUE, col_types = cols(.default = col_character())
) %>% readr::type_convert()

insert_size_metrics_ft <- readr::read_tsv(
  url_insert_metrics_ft, col_names = TRUE, col_types = cols(.default = col_character())
) %>% readr::type_convert()

insert_size_smry <- readr::read_tsv(
  url_insert_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::group_by(SAMPLE_NAME) %>%
  dplyr::mutate(TOTAL_READS = sum(READ_COUNT)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(`%_READS` = READ_COUNT / TOTAL_READS)

insert_size_smry_ft <- readr::read_tsv(
  url_insert_summary_ft, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::group_by(SAMPLE_NAME, FRAGMENT_LENGTH) %>%
  dplyr::mutate(TOTAL_READS = sum(READ_COUNT)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(`%_READS` = READ_COUNT / TOTAL_READS)

insert_metrics_by_gene <- readr::read_tsv(
  url_insert_metrics_by_gene, col_names = TRUE, col_types = cols(.default = col_character())
) %>% readr::type_convert()

idx_metrics_ft <- readr::read_tsv(
  url_idx_metrics_ft, col_names = TRUE, col_types = cols(.default = col_character())
) %>% readr::type_convert()

primer_set <- readr::read_tsv(
  url_primers, col_names = FALSE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(insert_size = X3 - X2)
```

```{r build_plots, eval = TRUE, include = FALSE}

# --- S2a: HPV subtype bar plot ---
plot_hpv16_bar <- manifest %>%
  dplyr::left_join(mrd_smry, by = "sample_uuid") %>%
  dplyr::filter(!duplicated(patient_id_mskcc)) %>%
  dplyr::mutate(
    hpv_type_wes_wgs = factor(hpv_type_wes_wgs, levels = sort(unique(hpv_type_wes_wgs)), ordered = TRUE)
  ) %>%
  ggplot(aes(x = hpv_type_wes_wgs, fill = hpv_type_wes_wgs)) +
  geom_bar(stat = "count", color = "black", alpha = 1) +
  scale_fill_manual(values = c(
    "HPV-16"  = "#377eb8",
    "HPV-18"  = "#e41a1c",
    "HPV-33"  = "#e41a1c",
    "HPV-35"  = "#e41a1c",
    "HPV-58"  = "#e41a1c",
    "Unknown" = "#737373"
  )) +
  xlab("") +
  ylab("Number of Patients") +
  scale_x_discrete() +
  scale_y_continuous(
    limits = c(0, 90),
    breaks = c(0, 15, 30, 45, 60, 75, 90),
    labels = c(0, "", 30, "", 60, "", 90)
  ) +
  theme_classic() +
  theme(
    axis.title.x = element_text(margin = ggplot2::margin(t = 20), size = 11),
    axis.title.y = element_text(margin = ggplot2::margin(r = 20), size = 11),
    axis.text.x  = element_text(size = 11, angle = 90, vjust = 0.5, hjust = 1),
    axis.text.y  = element_text(size = 11)
  ) +
  guides(fill = "none")

# --- S2b: ctDNA fraction box plot ---
plot_ctdna_frac <- smry_ft %>%
  dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
  dplyr::bind_rows(
    mutation_smry %>%
      dplyr::filter(FILTER == "PASS") %>%
      dplyr::group_by(Tumor_Sample_Barcode) %>%
      dplyr::summarize(mean_af = mean(t_maf), max_af = max(t_maf), .groups = "drop") %>%
      dplyr::rename(sample_name = Tumor_Sample_Barcode) %>%
      dplyr::left_join(manifest, by = "sample_name") %>%
      dplyr::filter(!(hpv_type_wes_wgs %in% c("HPV-16", "Unknown"))) %>%
      dplyr::left_join(
        mrd_smry_named %>%
          dplyr::select(sample_name, `MRD-Landmark_Result`, `MRD-Monitoring_MRD_Quantification`),
        by = "sample_name"
      ) %>%
      dplyr::filter(`MRD-Landmark_Result` == "PRESENT") %>%
      dplyr::mutate(Is_ctDNA = "Unknown") %>%
      dplyr::select(all_of(colnames(smry_ft)))
  ) %>%
  dplyr::mutate(Is_ctDNA = factor(Is_ctDNA, levels = c("+ve", "-ve", "Unknown"), ordered = TRUE)) %>%
  ggplot(aes(x = Is_ctDNA, y = 100 * `MRD-Monitoring_MRD_Quantification`, fill = Is_ctDNA)) +
  geom_boxplot(stat = "boxplot", outlier.shape = NA, fill = "white") +
  geom_jitter(stat = "identity", width = 0.15, height = 0, shape = 21, alpha = 0.85, size = 3) +
  scale_fill_manual(values = c("+ve" = "#377eb8", "-ve" = "#377eb8", "Unknown" = "#e41a1c")) +
  xlab("") +
  ylab("ctDNA Fraction (%)") +
  scale_x_discrete(
    breaks = c("+ve", "-ve", "Unknown"),
    labels = c("+ve", "-ve", "Outgroup")
  ) +
  scale_y_continuous(
    limits = c(0, 35),
    breaks = c(0, 5, 10, 15, 20, 25, 30),
    labels = c(0, "", 10, "", 20, "", 30)
  ) +
  geom_signif(
    stat        = "signif",
    comparisons = list(c("+ve", "-ve")),
    test        = "wilcox.test",
    test.args   = list(alternative = "two.sided", exact = FALSE),
    y_position  = 31,
    vjust       = -0.25,
    tip_length  = 0.01
  ) +
  theme_classic() +
  theme(
    axis.title.x = element_text(margin = ggplot2::margin(t = 20), size = 12),
    axis.title.y = element_text(margin = ggplot2::margin(r = 20), size = 12),
    axis.text.x  = element_text(size = 10),
    axis.text.y  = element_text(size = 12)
  ) +
  guides(fill = "none")

# --- S2c: HPV-16 mean insert size box plot ---
plot_insert_size <- insert_metrics_by_gene %>%
  dplyr::rename(sample_name = SAMPLE_NAME) %>%
  dplyr::filter(
    TARGET_REGION != "NC001526.4:3372-4794",
    grepl("NC001526.4", TARGET_REGION, fixed = TRUE)
  ) %>%
  dplyr::group_by(sample_name) %>%
  dplyr::summarize(MEAN_INSERT_SIZE = mean(MEAN_INSERT_SIZE), .groups = "drop") %>%
  dplyr::left_join(dplyr::select(smry_ft, sample_name, Is_ctDNA), by = "sample_name") %>%
  dplyr::mutate(
    Is_ctDNA = dplyr::coalesce(Is_ctDNA, "Unknown"),
    Is_ctDNA = factor(Is_ctDNA, levels = c("+ve", "-ve", "Unknown"), ordered = TRUE)
  ) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::filter(
    (Is_ctDNA %in% c("+ve", "-ve") & hpv_type_wes_wgs == "HPV-16") |
    (Is_ctDNA == "Unknown" & hpv_type_wes_wgs %in% c("HPV-18", "HPV-33", "HPV-35", "HPV-58"))
  ) %>%
  ggplot(aes(x = Is_ctDNA, y = MEAN_INSERT_SIZE, fill = Is_ctDNA)) +
  geom_boxplot(stat = "boxplot", outlier.shape = NA, fill = "white") +
  geom_jitter(stat = "identity", width = 0.15, height = 0, shape = 21, alpha = 0.85, size = 3) +
  scale_fill_manual(values = c("+ve" = "#377eb8", "-ve" = "#377eb8", "Unknown" = "#e41a1c")) +
  xlab("") +
  ylab("HPV-16 Mean Insert Size (bp)") +
  scale_x_discrete(
    breaks = c("+ve", "-ve", "Unknown"),
    labels = c("+ve", "-ve", "Outgroup")
  ) +
  scale_y_continuous(
    limits = c(20, 140),
    breaks = c(25, 50, 75, 100, 125),
    labels = c(25, 50, 75, 100, 125)
  ) +
  geom_signif(
    stat        = "signif",
    comparisons = list(c("+ve", "-ve")),
    test        = "wilcox.test",
    test.args   = list(alternative = "two.sided", exact = FALSE),
    y_position  = 130,
    vjust       = -0.25,
    tip_length  = 0.01
  ) +
  theme_classic() +
  theme(
    axis.title.x = element_text(margin = ggplot2::margin(t = 20), size = 12),
    axis.title.y = element_text(margin = ggplot2::margin(r = 20), size = 12),
    axis.text.x  = element_text(size = 10),
    axis.text.y  = element_text(size = 12)
  ) +
  guides(fill = "none")
```
<br/>
<br/>
```{r plot_30gy_barplot, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3, fig.width = 2.25, fig.cap = '<br/>**Supplementary Figure S2a** Bar plot of patient distribution by HPV subtype based on primary tumor analysis where HPV-16 predominates (89% of cases); HPV-18, -33, and -35 samples were too few to be used in the training set.'}

print(plot_hpv16_bar)
```
<br/>
<br/>
```{r plot_30gy_ctdna_frac, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3, fig.width = 2.25, fig.cap = '<br/>**Supplementary Figure S2b** Box plots comparing the ctDNA fraction between putative ctDNA positive and negative samples in the training and outgroup test set samples.'}

print(plot_ctdna_frac)
```
<br/>
<br/>
```{r plot_30gy_mean_insert_size, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3, fig.width = 2.25, fig.cap = '<br/>**Supplementary Figure S2c** Box plots comparing the mean insert size of read pairs aligned to the HPV-16 genome between putative ctDNA positive and negative samples in the training and outgroup test set samples.'}

print(plot_insert_size)
```
