---
title: "Supplementary Figure S9 - Dynamic response assessment using dual-assay ctDNA and imaging in HPV-associated OPC"
author:
  - name: David N Brown, Bill H Diplas
    affiliation: Memorial Sloan Kettering Cancer Center
output:
  html_document:
    theme: cerulean
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
suppressPackageStartupMessages({
  library("ggplot2")
  library("readr")
  library("dplyr")
  library("tidyr")
  library("magrittr")
  library("reshape2")
})

# --- Data paths ---
url_manifest                 <- "../data/manifest.txt"
url_mrd_summary              <- "../data/TM-2021-MSK-002_MRD_Results_Summary_20220825.txt"
url_preanalytical_conditions <- "../data/pre-analytical_conditions.txt"
url_hpv_type                 <- "../data/TM-2021-MSK-002_HPV_Typing_WES_WGS.txt"
url_no_node_dissection       <- "../data/patients_0_nodal_dissection.txt"
url_clinical                 <- "../data/clinical.txt"
url_mutation_summary         <- "../data/mutation_summary.maf"
url_idx_metrics_ft           <- "../data/idx_metrics_ft.txt"
url_posterior_probs          <- "../res/Posterior_Probability_ALL.txt"

target_contigs <- c(
  "HPV-16" = "NC001526.4",
  "HPV-18" = "NC001357.1",
  "HPV-31" = "J04353.1",
  "HPV-33" = "M12732.1",
  "HPV-35" = "X74477.1"
)

FRAGMENT_LENGTH_THRESHOLD <- 37

scientific_10 <- function(x) {
  parse(text = gsub("+", "", gsub("e", " %.% 10^", scales::scientific_format()(x)), fixed = TRUE))
}

# --- Helper: recode wk0/Pre-treatment timepoint labels to integer weeks ---
recode_weeks <- function(x) {
  dplyr::case_when(
    x %in% c("wk0", "Pre-treatment") ~ "0",
    x == "wk1" ~ "1",
    x == "wk2" ~ "2",
    x == "wk3" ~ "3"
  )
}

# --- Helper: shared ggplot structure for S9a-d panel plots ---
# df must have columns: patient_id_mskcc, timepoint_weeks_since_start_of_RT, value
timepoint_levels <- c("Pre-treatment", "wk1", "wk2", "wk3")

panel_plot <- function(df, y_col, y_scale, y_lab, x_angle = 90) {
  df %>%
    dplyr::filter(timepoint_weeks_since_start_of_RT %in% timepoint_levels) %>%
    dplyr::mutate(
      timepoint_weeks_since_start_of_RT = factor(
        timepoint_weeks_since_start_of_RT,
        levels = timepoint_levels,
        ordered = TRUE
      )
    ) %>%
    ggplot(aes(
      x    = timepoint_weeks_since_start_of_RT,
      y    = .data[[y_col]],
      fill = timepoint_weeks_since_start_of_RT
    )) +
    geom_line(aes(group = patient_id_mskcc), linewidth = 0.1, alpha = 1, color = "black") +
    geom_point(stat = "identity", shape = 21, size = 2, alpha = 1, color = "black") +
    scale_fill_brewer(type = "seq", palette = "YlGnBu", direction = -1) +
    scale_x_discrete(
      breaks = timepoint_levels,
      labels = c("Pre-treatment", "Week 1", "Week 2", "Week 3")
    ) +
    y_scale +
    xlab("") +
    ylab(y_lab) +
    theme_classic() +
    theme(
      axis.title.x = element_text(margin = ggplot2::margin(t = 20)),
      axis.title.y = element_text(margin = ggplot2::margin(r = 20)),
      axis.text.x  = element_text(size = 10, angle = x_angle, vjust = 0.5, hjust = 1),
      axis.text.y  = element_text(size = 10)
    ) +
    guides(fill = "none", color = "none")
}
```

```{r load_shared_data, eval = TRUE, include = FALSE}

manifest_raw <- readr::read_tsv(
  url_manifest, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::filter(!is.na(bam_file_name_hpv)) %>%
  dplyr::mutate(sample_uuid = paste0(sample_id_mskcc, "-", sample_id_invitae))

preanalytical_conditions <- readr::read_tsv(
  url_preanalytical_conditions, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

mrd_smry <- readr::read_tsv(
  url_mrd_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    sample_uuid = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE),
    sample_name = gsub("EP-D1-D1", "", Sample_ID_Archer, fixed = TRUE)
  )

hpv_smry <- readr::read_tsv(
  url_hpv_type, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    patient_id_mskcc = gsub("-T", "", patient_name, fixed = TRUE),
    patient_id_mskcc = gsub("155salv", "155", patient_id_mskcc, fixed = TRUE),
    hpv_type_wes     = gsub("HPV", "HPV-", hpv_type_wes, fixed = TRUE),
    hpv_type_wgs     = gsub("HPV", "HPV-", hpv_type_wgs, fixed = TRUE),
    hpv_type_wes_wgs = gsub("HPV", "HPV-", hpv_type_wes_wgs, fixed = TRUE),
    hpv_type_wes_wgs = dplyr::coalesce(hpv_type_wes_wgs, "Unknown")
  )

nodal_dissection_smry <- readr::read_tsv(
  url_no_node_dissection, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::rename(patient_id_mskcc = sample)

manifest <- manifest_raw %>%
  dplyr::left_join(preanalytical_conditions, by = "sample_id_mskcc") %>%
  dplyr::mutate(
    patient_id_mskcc = dplyr::case_when(
      is.na(patient_id_mskcc) & sample_id_mskcc == "21-144-03654" ~ "CTMS-164",
      TRUE ~ patient_id_mskcc
    ),
    sample_name = paste0(sample_id_mskcc, "-", sample_id_invitae)
  ) %>%
  dplyr::left_join(hpv_smry, by = "patient_id_mskcc")

mutation_smry <- readr::read_tsv(
  url_mutation_summary, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

clinical <- readr::read_tsv(
  url_clinical, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert()

posterior_probs <- readr::read_tsv(
  url_posterior_probs, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = floor(timepoint_days_since_start_of_RT / 7),
    timepoint_weeks_since_start_of_RT = dplyr::case_when(
      timepoint_weeks_since_start_of_RT < 0 ~ "Pre-treatment",
      TRUE ~ paste0("wk", timepoint_weeks_since_start_of_RT)
    )
  )

# --- Per-sample mutation AF summary ---
mut_af_smry <- mutation_smry %>%
  dplyr::filter(FILTER == "PASS") %>%
  dplyr::group_by(Tumor_Sample_Barcode) %>%
  dplyr::summarize(mean_af = mean(t_maf), .groups = "drop") %>%
  dplyr::rename(sample_name = Tumor_Sample_Barcode)

# --- Index metrics: per-sample per-contig aligned read pairs at target fragment length ---
idx_metrics_ft <- readr::read_tsv(
  url_idx_metrics_ft, col_names = TRUE, col_types = cols(.default = col_character())
) %>%
  readr::type_convert() %>%
  dplyr::select(
    sample_name     = SAMPLE_NAME,
    contig          = CHROMOSOME,
    aligned_reads   = ALIGNED_READS,
    fragment_length = FRAGMENT_LENGTH
  ) %>%
  dplyr::left_join(
    dplyr::tibble(contig = target_contigs, chromosome = names(target_contigs)),
    by = "contig"
  ) %>%
  dplyr::filter(fragment_length == FRAGMENT_LENGTH_THRESHOLD, !is.na(chromosome)) %>%
  dplyr::left_join(manifest, by = "sample_name") %>%
  dplyr::filter(chromosome == hpv_type_wes_wgs) %>%
  dplyr::left_join(mut_af_smry, by = "sample_name") %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = floor(timepoint_days_since_start_of_RT / 7),
    timepoint_weeks_since_start_of_RT = dplyr::case_when(
      timepoint_weeks_since_start_of_RT < 0 ~ "Pre-treatment",
      TRUE ~ paste0("wk", timepoint_weeks_since_start_of_RT)
    )
  )

# --- Per-patient HPV type lookup (used in clinical data joins) ---
hpv_type_per_patient <- manifest %>%
  dplyr::group_by(patient_id_mskcc) %>%
  dplyr::summarize(hpv_type_wes_wgs = unique(hpv_type_wes_wgs), .groups = "drop")
```

```{r build_plots_S9a, eval = TRUE, include = FALSE}

# --- S9a: MRI volume across weekly timepoints ---
plot_mri <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    `Pre-treatment` = MRI_rawdata_wk0,
    wk1             = MRI_rawdata_wk1,
    wk2             = MRI_rawdata_wk2,
    wk3             = MRI_rawdata_wk3
  ) %>%
  reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "MRI_volume") %>%
  dplyr::left_join(hpv_type_per_patient, by = "patient_id_mskcc") %>%
  tidyr::drop_na() %>%
  dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
  dplyr::mutate(MRI_volume = MRI_volume * 0.001) %>%
  panel_plot(
    y_col   = "MRI_volume",
    y_scale = scale_y_log10(labels = scientific_10),
    y_lab   = expression("MRI Volume (" ~ cm^3 ~ ")")
  )

# --- S9b: DW MRI mean ADC across weekly timepoints ---
plot_adc <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    `Pre-treatment` = ADC_Mean_wk0,
    wk1             = ADC_Mean_wk1,
    wk2             = ADC_Mean_wk2,
    wk3             = ADC_Mean_wk3
  ) %>%
  reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "ADC") %>%
  dplyr::left_join(hpv_type_per_patient, by = "patient_id_mskcc") %>%
  tidyr::drop_na() %>%
  dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
  panel_plot(
    y_col   = "ADC",
    y_scale = scale_y_log10(limits = c(0.4, 2.1), breaks = c(0.5, 1, 2), labels = c(0.5, 1, 2)),
    y_lab   = expression("ADC (" %.% 10^-3 ~ mm^2 ~ sec^-1 ~ ")")
  )

# --- S9a: ctDNA fraction (mean AF) across weekly timepoints ---
plot_maf <- idx_metrics_ft %>%
  dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
  dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(mean_af = mean(mean_af), .groups = "drop") %>%
  dplyr::mutate(mean_af_pct = (mean_af * 100) + 1e-3) %>%
  panel_plot(
    y_col   = "mean_af_pct",
    y_scale = scale_y_log10(
      limits = c(NA, 110),
      breaks = c(0.001, 0.01, 0.1, 1, 10, 100),
      labels = c(".001", ".01", ".1", "1", "10", "100")
    ),
    y_lab = "ctDNA Fraction (%)"
  )

# --- S9a: circulating HPV-16 read pairs across weekly timepoints ---
plot_readcounts <- idx_metrics_ft %>%
  dplyr::filter(hpv_type_wes_wgs == "HPV-16") %>%
  dplyr::group_by(patient_id_mskcc, timepoint_weeks_since_start_of_RT) %>%
  dplyr::summarize(aligned_reads = mean(log10(aligned_reads)), .groups = "drop") %>%
  panel_plot(
    y_col   = "aligned_reads",
    y_scale = scale_y_continuous(
      limits = c(0.5, 7),
      breaks = c(2, 3, 4, 5, 6, 7),
      labels = scientific_10(10^c(2, 3, 4, 5, 6, 7))
    ),
    y_lab = "cfDNA Aligned HPV Read Pairs"
  )
```

<br/>
<br/>

```{r plot_mri, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 3.65, fig.cap = '<br/>**Supplementary Figure S9a** Distribution of imaging (T2 MRI volume) across weekly measurements.'}

print(plot_mri)
```

<br/>
<br/>

```{r plot_adc, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 3.65, fig.cap = '<br/>**Supplementary Figure S9a** Distribution of imaging (DW MRI mean ADC) across weekly measurements.'}

print(plot_adc)
```

<br/>
<br/>

```{r plot_ctdna_frac, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 3.65, fig.cap = '<br/>**Supplementary Figure S9a** Distribution of ctDNA fraction inferred from PCM across weekly measurements.'}

print(plot_maf)
```

<br/>
<br/>

```{r plot_readcounts, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 3.65, fig.cap = '<br/>**Supplementary Figure S9a** Distribution of circulating HPV-16 read pairs across weekly measurements.'}

print(plot_readcounts)
```

```{r build_plot_S9c, eval = TRUE, include = FALSE}

# Helper: normalise a measure to baseline (week 0) for a given patient
normalise_to_baseline <- function(df, measure_col, patient_col = "patient_id_mskcc",
                                  week_col = "timepoint_weeks_since_start_of_RT") {
  baseline <- df %>%
    dplyr::filter(.data[[week_col]] == 0) %>%
    dplyr::select(all_of(c(patient_col, measure_col))) %>%
    dplyr::rename(baseline = !!measure_col)

  df %>%
    dplyr::left_join(baseline, by = patient_col) %>%
    dplyr::mutate(!!measure_col := .data[[measure_col]] / baseline) %>%
    dplyr::select(-baseline)
}

# --- PCM: mean AF normalised to pre-treatment ---
p_mrd <- idx_metrics_ft %>%
  dplyr::left_join(
    dplyr::select(mrd_smry, sample_name, `MRD-Monitoring_Result`),
    by = "sample_name"
  ) %>%
  dplyr::mutate(
    Is_ctDNA = dplyr::case_when(
      `MRD-Monitoring_Result` == "PRESENT" ~ "+ve",
      `MRD-Monitoring_Result` == "ABSENT"  ~ "-ve"
    )
  ) %>%
  dplyr::filter(
    patient_id_mskcc == "CTMS-30",
    timepoint_weeks_since_start_of_RT %in% c("wk0", "wk1", "wk2", "wk3")
  ) %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = recode_weeks(timepoint_weeks_since_start_of_RT)
  ) %>%
  readr::type_convert() %>%
  dplyr::select(
    patient_id_mskcc, timepoint_weeks_since_start_of_RT,
    measure = mean_af, Is_ctDNA
  ) %>%
  normalise_to_baseline("measure") %>%
  dplyr::mutate(assay = "PCM")

# --- HPV: aligned read pairs normalised to pre-treatment ---
p_hpv <- idx_metrics_ft %>%
  dplyr::left_join(
    dplyr::select(posterior_probs, sample_name, Is_ctDNA),
    by = "sample_name"
  ) %>%
  dplyr::filter(
    patient_id_mskcc == "CTMS-30",
    timepoint_weeks_since_start_of_RT %in% c("wk0", "wk1", "wk2", "wk3")
  ) %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = recode_weeks(timepoint_weeks_since_start_of_RT)
  ) %>%
  readr::type_convert() %>%
  dplyr::select(
    patient_id_mskcc, timepoint_weeks_since_start_of_RT,
    measure = aligned_reads, Is_ctDNA
  ) %>%
  normalise_to_baseline("measure") %>%
  dplyr::mutate(assay = "HPV")

# --- MRI: volume normalised and rescaled (increase from baseline) ---
p_mri <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    `Pre-treatment` = MRI_rawdata_wk0,
    wk1             = MRI_rawdata_wk1,
    wk2             = MRI_rawdata_wk2,
    wk3             = MRI_rawdata_wk3
  ) %>%
  reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "measure") %>%
  dplyr::filter(
    patient_id_mskcc == "CTMS-30",
    timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")
  ) %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = recode_weeks(timepoint_weeks_since_start_of_RT)
  ) %>%
  readr::type_convert() %>%
  normalise_to_baseline("measure") %>%
  dplyr::mutate(
    measure  = dplyr::if_else((measure - 1) < 0, 0, 2 * (measure - 1)),
    Is_ctDNA = "Not Applicable",
    assay    = "MRI"
  )

# --- ADC: mean ADC normalised and rescaled (increase from baseline) ---
p_adc <- clinical %>%
  dplyr::select(
    patient_id_mskcc,
    `Pre-treatment` = ADC_Mean_wk0,
    wk1             = ADC_Mean_wk1,
    wk2             = ADC_Mean_wk2,
    wk3             = ADC_Mean_wk3
  ) %>%
  reshape2::melt(variable.name = "timepoint_weeks_since_start_of_RT", value.name = "measure") %>%
  dplyr::filter(
    patient_id_mskcc == "CTMS-30",
    timepoint_weeks_since_start_of_RT %in% c("Pre-treatment", "wk1", "wk2", "wk3")
  ) %>%
  dplyr::mutate(
    timepoint_weeks_since_start_of_RT = recode_weeks(timepoint_weeks_since_start_of_RT)
  ) %>%
  readr::type_convert() %>%
  normalise_to_baseline("measure") %>%
  dplyr::mutate(
    measure  = dplyr::if_else((measure - 1) < 0, 0, 2 * (measure - 1)),
    Is_ctDNA = "Not Applicable",
    assay    = "ADC"
  )

plot_ctms30 <- dplyr::bind_rows(p_mrd, p_hpv, p_mri, p_adc) %>%
  dplyr::mutate(
    measure = measure * 100,
    assay   = factor(assay, levels = c("PCM", "HPV", "MRI", "ADC"), ordered = TRUE)
  ) %>%
  ggplot(aes(
    x     = timepoint_weeks_since_start_of_RT,
    y     = measure,
    shape = Is_ctDNA,
    color = assay
  )) +
  geom_line(
    mapping     = aes(x = timepoint_weeks_since_start_of_RT, y = measure, color = assay),
    stat        = "identity",
    linewidth   = 1.25,
    alpha       = 0.75,
    inherit.aes = FALSE
  ) +
  geom_point(stat = "identity", size = 4, fill = "white") +
  scale_shape_manual(values = c(21, 25, 22)) +
  scale_color_brewer(type = "qual", palette = 7) +
  scale_x_continuous(
    breaks = 0:3,
    labels = c("Pre-treat\n-ment", "Week 1", "Week 2", "Week 3")
  ) +
  scale_y_continuous(
    limits = c(-2, 105),
    breaks = c(0, 25, 50, 75, 100),
    labels = c(100, 75, 50, 25, 0),
    sec.axis = sec_axis(
      trans  = ~.,
      name   = "Relative Volume and ADC\nIncrease from Baseline (%)\n",
      breaks = c(0, 20, 40, 60, 80, 100),
      labels = c(0, 20, 40, 60, 80, 100) / 2
    )
  ) +
  xlab("") +
  ylab("Relative Decrease\nfrom Baseline (%)\n") +
  theme_classic() +
  theme(
    axis.title.x = element_text(margin = ggplot2::margin(t = 20)),
    axis.text.x  = element_text(margin = ggplot2::margin(t = 7), size = 12),
    axis.text.y  = element_text(size = 12)
  ) +
  guides(
    color = guide_legend(title = "Assay Modality", order = 1),
    shape = guide_legend(title = "ctDNA Status",   order = 2)
  )
```

<br/>
<br/>

```{r plot_ctms30, eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE, fig.align = 'left', fig.height = 3.5, fig.width = 6.5, fig.cap = '<br/>**Supplementary Figure S9c** ctDNA dynamic tracking showing the percentage change of imaging and genomic measures from baseline across weeks 1 to 3 for patient CTMS-30.'}

print(plot_ctms30)
```
